# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Ga9pnzmc_O3W_rWKGsaRNic-qKWLIcE
"""

# Multi-Sensor Fusion + Kalman Filtering + Reinforcement Learning
# Dataset: nuScenes mini

#CELL 0: We have to install setup for nuScenes mini

# Installing the nuScenes toolkit used to read the dataset.
!pip install -q nuscenes-devkit

# Now we have to mount Google Drive so Colab can access the dataset file.
from google.colab import drive
drive.mount('/content/drive')

# Start with a clean local data folder.
# This removes only the extracted local copy, not the files stored in Google Drive.
!rm -rf /content/data
!mkdir -p /content/data

# Extracting the nuScenes mini dataset.
!tar -xvzf /content/drive/MyDrive/Grad_Project_Dataset/v1.0-mini.tgz -C /content/data

# checking the extracted folder size.
!du -sh /content/data


#CELL 1: Importing all the required libraries

import numpy as np, pandas as pd, matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import Patch
from matplotlib.lines import Line2D
from mpl_toolkits.mplot3d import Axes3D
from scipy.spatial.transform import Rotation
from scipy.linalg import qr
from scipy.stats import wilcoxon
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import GroupKFold
from sklearn.preprocessing import StandardScaler
from collections import deque
import warnings, random, copy, time, os
warnings.filterwarnings('ignore')
import torch, torch.nn as nn, torch.optim as optim, torch.nn.functional as TF

# for the color palette used consistently across plots
C = {'imu':'#C0392B','gps':'#27AE60','radar':'#2980B9','ekf':'#D4770B','ukf':'#7D3C98',
     'ckf':'#148F77','sac':'#CB4335','td3':'#2471A3','ppo':'#229954','gt':'#2C3E50',
     'fusion':'#6C3483','attack':'#922B21','defense':'#1A9C85','accent':'#E67E22'}

plt.rcParams.update({'figure.facecolor':'white','axes.facecolor':'#F8F9FA','axes.edgecolor':'#7F8C8D',
    'axes.linewidth':1.0,'axes.grid':True,'grid.alpha':0.25,'grid.color':'#D5D8DC','grid.linestyle':'--',
    'font.family':'serif','font.size':11,'axes.titlesize':13,'figure.dpi':130,'savefig.dpi':250,
    'savefig.bbox':'tight'})
print("All imports loaded.")


# CELL 2: Loading nuScenes

from nuscenes.nuscenes import NuScenes
from nuscenes.utils.data_classes import RadarPointCloud
nusc = NuScenes(version='v1.0-mini', dataroot='/content/data', verbose=True)
selected_scenes = nusc.scene
print(f"Scenes: {len(selected_scenes)} | Samples: {len(nusc.sample)}")

# CELL 3: Extracting required Sensor Data

RADAR_CH = ['RADAR_FRONT','RADAR_FRONT_LEFT','RADAR_FRONT_RIGHT','RADAR_BACK_LEFT','RADAR_BACK_RIGHT']

def quat_to_euler(q0,q1,dt):
    r0=Rotation.from_quat([q0[1],q0[2],q0[3],q0[0]]); r1=Rotation.from_quat([q1[1],q1[2],q1[3],q1[0]])
    return (r0.inv()*r1).as_euler('xyz')/dt if dt>0 else np.zeros(3)

def radar_feat(nusc,tok):
    try:
        sd=nusc.get('sample_data',tok); pc=RadarPointCloud.from_file(nusc.dataroot+'/'+sd['filename']); p=pc.points
        if p.shape[1]==0: return {k:0 for k in ['radar_range_mean','radar_range_std','radar_vel_mean','radar_vel_std','radar_rcs_mean','radar_rcs_std','radar_count']}
        rng=np.sqrt(p[0]**2+p[1]**2)
        return dict(radar_range_mean=np.mean(rng),radar_range_std=np.std(rng),radar_vel_mean=np.mean(p[8]),radar_vel_std=np.std(p[8]),radar_rcs_mean=np.mean(p[5]),radar_rcs_std=np.std(p[5]),radar_count=p.shape[1])
    except: return {k:0 for k in ['radar_range_mean','radar_range_std','radar_vel_mean','radar_vel_std','radar_rcs_mean','radar_rcs_std','radar_count']}

def extract_scene(nusc,scene):
    s=nusc.get('sample',scene['first_sample_token']); rows=[]; pe=None; pt=None
    while True:
        sd=nusc.get('sample_data',s['data']['RADAR_FRONT']); ego=nusc.get('ego_pose',sd['ego_pose_token'])
        ts=s['timestamp']/1e6; pos=ego['translation']; q=ego['rotation']
        row=dict(timestamp=ts,scene_name=scene['name'],gps_x=pos[0],gps_y=pos[1],gps_z=pos[2])
        dt=(ts-pt) if pt else 0.5; row['dt']=max(dt,0.01)
        if pe: pp=pe['translation']; row['vx']=(pos[0]-pp[0])/row['dt']; row['vy']=(pos[1]-pp[1])/row['dt']; row['vz']=(pos[2]-pp[2])/row['dt']
        else: row['vx']=row['vy']=row['vz']=0.
        if pe and rows: row['ax']=(row['vx']-rows[-1].get('vx',0))/row['dt']; row['ay']=(row['vy']-rows[-1].get('vy',0))/row['dt']; row['az']=(row['vz']-rows[-1].get('vz',0))/row['dt']
        else: row['ax']=row['ay']=row['az']=0.
        if pe: g=quat_to_euler(pe['rotation'],q,row['dt']); row['gyro_x'],row['gyro_y'],row['gyro_z']=g
        else: row['gyro_x']=row['gyro_y']=row['gyro_z']=0.
        agg={k:[] for k in ['radar_range_mean','radar_range_std','radar_vel_mean','radar_vel_std','radar_rcs_mean','radar_rcs_std','radar_count']}
        for ch in RADAR_CH:
            if ch in s['data']:
                rf=radar_feat(nusc,s['data'][ch])
                for k,v in rf.items(): agg[k].append(v)
        for k in agg: vl=[v for v in agg[k] if v!=0]; row[k]=np.mean(vl) if vl else 0.
        rows.append(row); pe=ego; pt=ts
        if s['next']=='': break
        s=nusc.get('sample',s['next'])
    return pd.DataFrame(rows)

print("Extracting sensor data")
scene_dfs=[]
for i,sc in enumerate(selected_scenes):
    df_sc=extract_scene(nusc,sc); df_sc['scene_id']=i; scene_dfs.append(df_sc)
    print(f"  Scene {i}: {len(df_sc)} samples")
df_all=pd.concat(scene_dfs,ignore_index=True)
print(f"Total: {len(df_all)} samples")


# CELL 4: Features + Labels + TopK

WINDOW=5
def compute_features(df):
    rows=[]
    for i in range(len(df)-WINDOW+1):
        w=df.iloc[i:i+WINDOW]; r={}
        for col in ['ax','ay','az','gyro_x','gyro_y','gyro_z']:
            r[f'imu_{col}_mean']=w[col].mean(); r[f'imu_{col}_std']=w[col].std()
            r[f'imu_{col}_max']=w[col].max(); r[f'imu_{col}_min']=w[col].min()
            r[f'imu_{col}_range']=w[col].max()-w[col].min()
        am=np.sqrt(w['ax']**2+w['ay']**2+w['az']**2); gm=np.sqrt(w['gyro_x']**2+w['gyro_y']**2+w['gyro_z']**2)
        r['imu_acc_mag_mean']=am.mean(); r['imu_acc_mag_std']=am.std()
        r['imu_gyro_mag_mean']=gm.mean(); r['imu_gyro_mag_std']=gm.std()
        for col in ['vx','vy','vz']: r[f'gps_{col}_mean']=w[col].mean(); r[f'gps_{col}_std']=w[col].std()
        sp=np.sqrt(w['vx']**2+w['vy']**2); r['gps_speed_mean']=sp.mean(); r['gps_speed_std']=sp.std()
        r['gps_dx']=w['gps_x'].iloc[-1]-w['gps_x'].iloc[0]; r['gps_dy']=w['gps_y'].iloc[-1]-w['gps_y'].iloc[0]
        r['gps_displacement']=np.sqrt(r['gps_dx']**2+r['gps_dy']**2)
        h=np.arctan2(w['vy'].values,w['vx'].values+1e-8); r['gps_heading_change']=np.abs(h[-1]-h[0])
        pl=np.sum(np.sqrt(np.diff(w['gps_x'])**2+np.diff(w['gps_y'])**2))
        r['gps_tortuosity']=pl/(r['gps_displacement']+1e-8)
        r['gps_curvature_proxy']=r['gps_heading_change']/(pl+1e-8)
        r['gps_stop_ratio']=np.mean(sp<0.75)
        for col in ['radar_range_mean','radar_range_std','radar_vel_mean','radar_vel_std','radar_rcs_mean','radar_rcs_std','radar_count']:
            r[f'{col}_w_mean']=w[col].mean(); r[f'{col}_w_std']=w[col].std()
        r['radar_motion_ratio']=np.mean(np.abs(w['radar_vel_mean'])>0.5)
        r['radar_density']=np.mean(w['radar_count']); r['radar_energy']=np.mean(w['radar_vel_mean']**2)
        r['scene_id']=w['scene_id'].iloc[0]; mid=WINDOW//2
        r['gt_x']=w['gps_x'].iloc[mid]; r['gt_y']=w['gps_y'].iloc[mid]; r['gt_z']=w['gps_z'].iloc[mid]
        r['gt_vx']=w['vx'].iloc[mid]; r['gt_vy']=w['vy'].iloc[mid]
        rows.append(r)
    return pd.DataFrame(rows)

feature_dfs=[]
for sid in sorted(df_all['scene_id'].unique()):
    feat=compute_features(df_all[df_all['scene_id']==sid].reset_index(drop=True)).fillna(0).replace([np.inf,-np.inf],0)
    feature_dfs.append(feat)
df_features=pd.concat(feature_dfs,ignore_index=True)

imu_cols=[c for c in df_features.columns if c.startswith('imu_')]
gps_cols=[c for c in df_features.columns if c.startswith('gps_')]
radar_cols=[c for c in df_features.columns if c.startswith('radar_')]
all_feature_cols=imu_cols+gps_cols+radar_cols

speed=np.sqrt(df_features['gps_vx_mean']**2+df_features['gps_vy_mean']**2)
heading=df_features['gps_heading_change']; acc_mag=df_features['imu_acc_mag_mean']
labels=np.zeros(len(df_features),dtype=int)
for i in range(len(df_features)):
    if speed.iloc[i]<0.8: labels[i]=0
    elif heading.iloc[i]>0.20 or acc_mag.iloc[i]>1.2: labels[i]=2
    else: labels[i]=1
df_features['label']=labels; label_names=['Stopped','Cruising','Turning']

X_all=df_features[all_feature_cols].values; y_all=df_features['label'].values
scaler=StandardScaler(); X_sc=scaler.fit_transform(X_all)
gb_ranker=GradientBoostingClassifier(n_estimators=100,max_depth=4,random_state=42).fit(X_sc,y_all)
feat_imp=pd.DataFrame({'feature':all_feature_cols,'importance':gb_ranker.feature_importances_}).sort_values('importance',ascending=False)
K=25; top_k_features=feat_imp.head(K)['feature'].tolist()
topk_imp=feat_imp.head(K)['importance'].values

# Train/test split by scene
train_scenes_ids=[0,1,2,3,4,5,6]; test_scenes_ids=[7,8,9]
train_df=df_features[df_features['scene_id'].isin(train_scenes_ids)].copy()
test_df=df_features[df_features['scene_id'].isin(test_scenes_ids)].copy()
X_train_h=train_df[top_k_features].values; X_test_h=test_df[top_k_features].values
y_train_h=train_df['label'].values; y_test_h=test_df['label'].values
tmean=X_train_h.mean(0); tstd=X_train_h.std(0)+1e-8
X_train_h=(X_train_h-tmean)/tstd; X_test_h=(X_test_h-tmean)/tstd

print(f"Features: {len(all_feature_cols)} | Train: {len(train_df)} | Test: {len(test_df)}")
print(f"Classes: {[(n,(labels==i).sum()) for i,n in enumerate(label_names)]}")


# CELL 5: Hopfield Network #

class HopfieldNetwork:
    def __init__(s,n=25): s.n=n; s.weights=np.zeros((n,n)); s.stored_patterns={}
    def train(s,pats):
        s.stored_patterns=pats; s.weights=np.zeros((s.n,s.n))
        for p in pats.values(): f=p.flatten(); s.weights+=np.outer(f,f)
        np.fill_diagonal(s.weights,0); s.weights/=len(pats)
    def recall(s,inp,it=20):
        st=inp.flatten().copy()
        for _ in range(it):
            prev=st.copy()
            for i in range(s.n): st[i]=1 if np.dot(s.weights[i],st)>=0 else -1
            if np.array_equal(st,prev): break
        return st
    def classify(s,inp):
        r=s.recall(inp); bl,bs=None,-np.inf
        for l,p in s.stored_patterns.items():
            d=np.linalg.norm(r-p.flatten()); sim=1./(1.+d)
            if sim>bs: bs,bl=sim,l
        return bl,bs

def binarize_features(f,t=None):
    if t is None: t=np.median(f)
    return np.where(f>=t,1,-1)

reference_patterns={}
for cls in np.unique(y_train_h):
    avg=X_train_h[y_train_h==cls].mean(0)
    reference_patterns[cls]=binarize_features(avg).reshape(5,5)

hopfield=HopfieldNetwork(); hopfield.train(reference_patterns)
hop_preds=np.array([hopfield.classify(binarize_features(x))[0] for x in X_test_h])
hop_acc=accuracy_score(y_test_h,hop_preds)

# Classification results
results={}; cm_store={}
for name,cols in [('IMU Only',imu_cols),('GPS Only',gps_cols),('Radar Only',radar_cols),
                   ('IMU+GPS',imu_cols+gps_cols),('IMU+Radar',imu_cols+radar_cols),('GPS+Radar',gps_cols+radar_cols)]:
    sl=StandardScaler(); Xtr=sl.fit_transform(train_df[cols].values); Xte=sl.transform(test_df[cols].values)
    rf=RandomForestClassifier(n_estimators=200,random_state=42).fit(Xtr,train_df['label'].values)
    pred=rf.predict(Xte); results[name]=accuracy_score(test_df['label'].values,pred)
    cm_store[name]=confusion_matrix(test_df['label'].values,pred)

sl_all=StandardScaler(); Xtr_a=sl_all.fit_transform(train_df[all_feature_cols].values)
Xte_a=sl_all.transform(test_df[all_feature_cols].values); ytr=train_df['label'].values; yte=test_df['label'].values
rf_all=RandomForestClassifier(n_estimators=300,random_state=42).fit(Xtr_a,ytr)
results['3 Sensor RF']=accuracy_score(yte,rf_all.predict(Xte_a)); cm_store['3 Sensor RF']=confusion_matrix(yte,rf_all.predict(Xte_a))
gb_all=GradientBoostingClassifier(n_estimators=200,max_depth=4,random_state=42).fit(Xtr_a,ytr)
results['3 Sensor GB']=accuracy_score(yte,gb_all.predict(Xte_a)); cm_store['3 Sensor GB']=confusion_matrix(yte,gb_all.predict(Xte_a))
results['3 Sensor Hopfield']=hop_acc; cm_store['3-Sensor Hopfield']=confusion_matrix(y_test_h,hop_preds)

# Neuromorphic Fusion
def hop_sims(X,hop):
    return np.array([[1./(1.+np.linalg.norm(hop.recall(np.where(x>=np.median(x),1,-1))-hop.stored_patterns[c].flatten()))
                       for c in sorted(hop.stored_patterns)] for x in X])
sims_tr=hop_sims(X_train_h,hopfield); sims_te=hop_sims(X_test_h,hopfield)
X_tr_n=np.hstack([X_train_h,sims_tr]); X_te_n=np.hstack([X_test_h,sims_te])
gb_n=GradientBoostingClassifier(n_estimators=250,max_depth=4,random_state=42).fit(X_tr_n,y_train_h)
neuro_pred=gb_n.predict(X_te_n); neuro_acc=accuracy_score(y_test_h,neuro_pred)
results['Neuromorphic Fusion']=neuro_acc; cm_store['Neuromorphic Fusion']=confusion_matrix(y_test_h,neuro_pred)

print("\nClassification Results")
for m,a in sorted(results.items(),key=lambda x:x[1],reverse=True): print(f"  {m:25s} {a*100:.2f}%")
print(f"\n  Paper 1 reference: 98.98%")
if neuro_acc>0.9898: print(f" Neuromorphic Fusion ({neuro_acc*100:.2f}%)")


# CELL 6: Phase 1 Outputs and plots

# FIG 1: Feature Importance + Sensor
fig,(ax1,ax2)=plt.subplots(1,2,figsize=(20,8),gridspec_kw={'width_ratios':[2.5,1]})
top25=feat_imp.head(25).iloc[::-1]
tc=[C['imu'] if f.startswith('imu') else C['gps'] if f.startswith('gps') else C['radar'] for f in top25['feature']]
ax1.barh(range(25),top25['importance'],color=tc,edgecolor='white',height=0.7,alpha=0.85)
ax1.set_yticks(range(25)); ax1.set_yticklabels(top25['feature'],fontsize=8)
ax1.set_xlabel('Importance',fontweight='bold')
ax1.set_title('Top-25 Feature Importance (TopK Attention)',fontsize=13,fontweight='bold')
ax1.legend(handles=[Patch(facecolor=C['imu'],label='IMU'),Patch(facecolor=C['gps'],label='GPS'),Patch(facecolor=C['radar'],label='Radar')],loc='lower right')
si={'IMU':feat_imp[feat_imp['feature'].str.startswith('imu')]['importance'].sum(),
    'GPS':feat_imp[feat_imp['feature'].str.startswith('gps')]['importance'].sum(),
    'Radar':feat_imp[feat_imp['feature'].str.startswith('radar')]['importance'].sum()}
ax2.pie(si.values(),labels=si.keys(),colors=[C['imu'],C['gps'],C['radar']],autopct='%1.1f%%',startangle=90,
        textprops={'fontsize':12,'fontweight':'bold'})
ax2.set_title('Sensor Contribution',fontsize=13,fontweight='bold')
plt.savefig('fig01_features.png',dpi=250,bbox_inches='tight'); plt.show()

# FIG 2: Hopfield 3D Surface
fig=plt.figure(figsize=(20,6))
ax3d=fig.add_subplot(131,projection='3d')
X_grid,Y_grid=np.meshgrid(range(5),range(5))
for ci,(cls,pat) in enumerate(reference_patterns.items()):
    p=pat.reshape(5,5); ax3d.plot_surface(X_grid,Y_grid,p+ci*2.5,alpha=0.7,label=label_names[cls])
ax3d.set_xlabel('Feature X'); ax3d.set_ylabel('Feature Y'); ax3d.set_zlabel('Value')
ax3d.set_title('(a) Neuron State Space\n(3D Pattern Surface)',fontsize=11,fontweight='bold')

ax3d2=fig.add_subplot(132,projection='3d')
W_x,W_y=np.meshgrid(range(25),range(25))
ax3d2.plot_surface(W_x,W_y,hopfield.weights,cmap='coolwarm',alpha=0.8)
ax3d2.set_xlabel('Neuron X'); ax3d2.set_ylabel('Neuron Y'); ax3d2.set_zlabel('Weight')
ax3d2.set_title('(b) Weight Output\n(Hebbian Learned)',fontsize=11,fontweight='bold')

ax2d=fig.add_subplot(133)
im=ax2d.imshow(hopfield.weights,cmap='RdBu_r',aspect='equal')
ax2d.set_title('(c) Weight Matrix\n(2D View)',fontsize=11,fontweight='bold')
plt.colorbar(im,ax=ax2d,fraction=0.046)
plt.suptitle('Hopfield Neural Network: Stored Patterns and Weights',fontsize=13,fontweight='bold',y=1.02)
plt.savefig('fig02_hopfield_3d.png',dpi=250,bbox_inches='tight'); plt.show()

# FIG 3: Classification Comparison and Confusion Matrices
fig=plt.figure(figsize=(22,11))
gs=gridspec.GridSpec(2,1,height_ratios=[1.2,1],hspace=0.35)
ax0=fig.add_subplot(gs[0])
ms=sorted(results.items(),key=lambda x:x[1],reverse=True); nms=[m[0] for m in ms]; acs=[m[1]*100 for m in ms]
bc=['#6C3483' if 'Neuro' in n else '#148F77' if '3-Sensor' in n else '#2471A3' if '+' in n else C['imu'] if 'IMU' in n else C['gps'] if 'GPS' in n else C['radar'] for n in nms]
bars=ax0.bar(range(len(nms)),acs,color=bc,edgecolor='white',width=0.65,alpha=0.85)
ax0.axhline(98.98,color=C['attack'],linestyle='--',linewidth=2,alpha=0.8,label='Paper 1: 98.98%')
for b,a in zip(bars,acs): ax0.text(b.get_x()+b.get_width()/2,a+0.3,f'{a:.1f}%',ha='center',fontsize=9,fontweight='bold')
ax0.set_xticks(range(len(nms))); ax0.set_xticklabels(nms,rotation=25,ha='right',fontsize=9)
ax0.set_ylabel('Accuracy (%)',fontweight='bold'); ax0.set_ylim([50,104])
ax0.set_title('Classification: Single, Multi-Sensor and Neuromorphic Fusion',fontsize=14,fontweight='bold')
ax0.legend(fontsize=10)

gs2=gridspec.GridSpecFromSubplotSpec(1,5,subplot_spec=gs[1],wspace=0.25)
cm_show=[('IMU Only',cm_store.get('IMU Only'),results.get('IMU Only',0)),
         ('Hopfield',cm_store.get('3-Sensor Hopfield'),hop_acc),
         ('3-Sensor RF',cm_store.get('3-Sensor RF'),results.get('3-Sensor RF',0)),
         ('3-Sensor GB',cm_store.get('3-Sensor GB'),results.get('3-Sensor GB',0)),
         ('Neuro Fusion',cm_store.get('Neuromorphic Fusion'),neuro_acc)]
cmaps=['Blues','Greys','Greens','Oranges','Purples']; sn=['Stop','Cruise','Turn']
for idx,(title,cm,acc) in enumerate(cm_show):
    ax=fig.add_subplot(gs2[0,idx])
    if cm is None: ax.text(0.5,0.5,'N/A',ha='center'); continue
    cmn=cm.astype(float)/np.maximum(cm.sum(1,keepdims=True),1.)
    ax.imshow(cmn,cmap=cmaps[idx],vmin=0,vmax=1)
    ax.set_xticks(range(3)); ax.set_yticks(range(3)); ax.set_xticklabels(sn,fontsize=8); ax.set_yticklabels(sn,fontsize=8)
    ax.set_xlabel('Predicted',fontsize=9); ax.set_ylabel('True',fontsize=9)
    ax.set_title(f'{title}\n{acc*100:.1f}%',fontsize=10,fontweight='bold')
    for ii in range(3):
        for jj in range(3):
            c='white' if cmn[ii,jj]>0.55 else 'black'
            ax.text(jj,ii,f'{cm[ii,jj]}\n({cmn[ii,jj]*100:.0f}%)',ha='center',va='center',fontsize=8,color=c,fontweight='bold')
plt.savefig('fig03_classification.png',dpi=250,bbox_inches='tight'); plt.show()

# FIG 4: CV Box Plot
cv_res={}; groups=df_features['scene_id'].values; gkf=GroupKFold(n_splits=5)
for name,cols in [('IMU\nOnly',imu_cols),('GPS\nOnly',gps_cols),('Radar\nOnly',radar_cols),
                   ('IMU+\nGPS',imu_cols+gps_cols),('IMU+\nRadar',imu_cols+radar_cols),
                   ('GPS+\nRadar',gps_cols+radar_cols),('3-Sensor\nFusion',all_feature_cols)]:
    X=df_features[cols].values; y=df_features['label'].values; scores=[]
    for tr,te in gkf.split(X,y,groups):
        sl=StandardScaler(); Xtr=sl.fit_transform(X[tr]); Xte=sl.transform(X[te])
        gb=GradientBoostingClassifier(n_estimators=250,learning_rate=0.05,max_depth=3,random_state=42).fit(Xtr,y[tr])
        scores.append(accuracy_score(y[te],gb.predict(Xte)))
    cv_res[name]=np.array(scores)

fig,ax=plt.subplots(figsize=(13,6))
cvd=[cv_res[k]*100 for k in cv_res]
bp=ax.boxplot(cvd,patch_artist=True,widths=0.55,medianprops=dict(color='black',linewidth=2))
bcolors=[C['imu'],C['gps'],C['radar'],'#5DADE2','#48C9B0',C['accent'],C['fusion']]
for p,c in zip(bp['boxes'],bcolors): p.set_facecolor(c); p.set_alpha(0.75)
for i,data in enumerate(cvd):
    x=np.random.normal(i+1,0.04,len(data)); ax.scatter(x,data,alpha=0.7,s=40,color=C['gt'],edgecolors='white',zorder=3)
    ax.text(i+1,np.median(data)+1.5,f'{np.median(data):.1f}%',ha='center',fontsize=10,fontweight='bold',color=C['attack'])
ax.set_xticklabels(cv_res.keys(),fontsize=11); ax.set_ylabel('Accuracy (%)',fontweight='bold'); ax.set_ylim([40,100])
ax.set_title('5-Fold GroupKFold Cross-Validation: More Sensors → Higher Accuracy',fontsize=13,fontweight='bold')
plt.savefig('fig04_cv_boxplot.png',dpi=250,bbox_inches='tight'); plt.show()
print("Phase 1 Results.")


# CELL 7: Kalman Filters

class BaseKF:
    Q0=np.diag([.08,.08,.04,.4,.4,.15]); Rg0=np.diag([1.,1.,.5]); Rr0=np.diag([2.5,2.5])
    def __init__(s): s.state=np.zeros(6); s._P=np.eye(6)*10.; s.Q=s.Q0.copy(); s.R_gps=s.Rg0.copy(); s.R_radar=s.Rr0.copy()
    def set_noise(s,qs=1.,rgs=1.,rrs=1.): s.Q=s.Q0*max(float(qs),1e-4); s.R_gps=s.Rg0*max(float(rgs),1e-4); s.R_radar=s.Rr0*max(float(rrs),1e-4)
    def get_state(s): return s.state.copy()
    @staticmethod
    def _kin(x,ax,ay,az,dt): return np.array([x[0]+x[3]*dt+.5*ax*dt*dt,x[1]+x[4]*dt+.5*ay*dt*dt,x[2]+x[5]*dt+.5*az*dt*dt,x[3]+ax*dt,x[4]+ay*dt,x[5]+az*dt])
    @staticmethod
    def _rpd(M,e=1e-8): M=.5*(M+M.T); w,V=np.linalg.eigh(M); return (V*np.maximum(w,e))@V.T
    @staticmethod
    def _sch(M):
        M=.5*(M+M.T)
        try: return np.linalg.cholesky(M)
        except: return np.linalg.cholesky(BaseKF._rpd(M)+np.eye(len(M))*1e-6)

class EKF(BaseKF):
    def predict(s,ax,ay,az,dt):
        s.state=s._kin(s.state,ax,ay,az,dt); F=np.eye(6); F[0,3]=F[1,4]=F[2,5]=dt
        s._P=F@s._P@F.T+s.Q; s._P=.5*(s._P+s._P.T); return s.get_state()
    def _upd(s,z,H,R):
        inn=z-H@s.state; S=H@s._P@H.T+R; Si=np.linalg.inv(S); K=s._P@H.T@Si
        s.state+=K@inn; I_=np.eye(6)-K@H; s._P=I_@s._P@I_.T+K@R@K.T; s._P=.5*(s._P+s._P.T)
        return s.get_state(),float(inn@Si@inn)
    def update_gps(s,z): H=np.zeros((3,6)); H[0,0]=H[1,1]=H[2,2]=1.; return s._upd(z,H,s.R_gps)
    def update_radar(s,z): H=np.zeros((2,6)); H[0,3]=H[1,4]=1.; return s._upd(z,H,s.R_radar)

class UKF(BaseKF):
    def _init__(s,a=1e-3,b=2.,k=0.):
        super().__init__(); n=6; s.lam=a*a*(n+k)-n
        s.Wm=np.full(13,1./(2*(n+s.lam))); s.Wc=s.Wm.copy()
        s.Wm[0]=s.lam/(n+s.lam); s.Wc[0]=s.Wm[0]+(1-a*a+b); s._sc=np.sqrt(n+s.lam)
    def _sig(s):
        S=s._sch(s._P); X=np.zeros((13,6)); X[0]=s.state
        for i in range(6): X[i+1]=s.state+s._sc*S[:,i]; X[7+i]=s.state-s._sc*S[:,i]
        return X
    def predict(s,ax,ay,az,dt):
        X=s._sig(); Xp=np.array([s._kin(x,ax,ay,az,dt) for x in X])
        s.state=s.Wm@Xp; d=Xp-s.state; s._P=(d.T*s.Wc)@d+s.Q; s._P=s._rpd(s._P); return s.get_state()
    def _upd(s,z,idx,R):
        X=s._sig(); Z=X[:,idx]; zp=s.Wm@Z; dz=Z-zp; dx=X-s.state
        S=(dz.T*s.Wc)@dz+R; Cr=(dx.T*s.Wc)@dz; Si=np.linalg.inv(S); K=Cr@Si
        inn=z-zp; s.state+=K@inn; s._P-=K@S@K.T; s._P=s._rpd(s._P); return s.get_state(),float(inn@Si@inn)
    def update_gps(s,z): return s._upd(z,[0,1,2],s.R_gps)
    def update_radar(s,z): return s._upd(z,[3,4],s.R_radar)

class CKF(BaseKF):
    def _init_(s):
        super()._init_(); s.n=6; s.m=12; s.sn=np.sqrt(6.); s._S=np.linalg.cholesky(s._P)
    def _cp(s):
        pts=np.zeros((12,6))
        for i in range(6): pts[i]=s.state+s.sn*s._S[:,i]; pts[6+i]=s.state-s.sn*s._S[:,i]
        return pts
    def _tri(s,A):
        _,R=qr(A.T,mode='economic'); L=R.T; d=np.diag(L); return L*np.where(d<0,-1.,1.)[None,:]
    def predict(s,ax,ay,az,dt):
        X=s._cp(); Xp=np.array([s._kin(x,ax,ay,az,dt) for x in X])
        s.state=Xp.mean(0); W=(Xp-s.state).T/np.sqrt(s.m)
        SQ=np.linalg.cholesky(s.Q); s._S=s._tri(np.hstack([W,SQ])); s._P=s._S@s._S.T; return s.get_state()
    def _upd(s,z,idx,R):
        X=s._cp(); Z=X[:,idx]; zp=Z.mean(0)
        dZ=(Z-zp).T/np.sqrt(s.m); dX=(X-s.state).T/np.sqrt(s.m)
        SR=np.linalg.cholesky(R); Szz=s._tri(np.hstack([dZ,SR])); Pxz=dX@dZ.T
        tmp=np.linalg.solve(Szz,Pxz.T); K=np.linalg.solve(Szz.T,tmp).T
        inn=z-zp; s.state+=K@inn; s._S=s._tri(np.hstack([dX-K@dZ,K@SR])); s._P=s._S@s._S.T
        Sf=Szz@Szz.T; return s.get_state(),float(inn@np.linalg.solve(Sf,inn))
    def update_gps(s,z): return s._upd(z,[0,1,2],s.R_gps)
    def update_radar(s,z): return s._upd(z,[3,4],s.R_radar)

FILTERS={'EKF':EKF,'UKF':UKF,'CKF':CKF}


# CELL 8: KF Evaluation + Baselines

def radar_vel_meas(row,filt_state):
    vx,vy=filt_state[3],filt_state[4]; h=np.arctan2(vy,vx+1e-8)
    if np.sqrt(vx**2+vy**2)<1e-3: h=np.arctan2(row['vy'],row['vx']+1e-8)
    if row['radar_vel_mean']==0: return None
    sp=abs(row['radar_vel_mean']); return np.array([sp*np.cos(h),sp*np.sin(h)])

def run_filter(FC,sd,spoof=None):
    f=FC(); r0=sd.iloc[0]; f.state=np.array([r0['gps_x'],r0['gps_y'],r0['gps_z'],0,0,0],dtype=float)
    ests,niss,errs,verrs,att_flags=[f.get_state()],[0.],[0.],[0.],[False]
    for k in range(1,len(sd)):
        r=sd.iloc[k]; f.predict(r['ax'],r['ay'],r['az'],r['dt'])
        z=np.array([r['gps_x'],r['gps_y'],r['gps_z']]); attacked=False
        if spoof: attacked,z=spoof.apply(k,z)
        _,nis=f.update_gps(z); niss.append(nis)
        zr=radar_vel_meas(r,f.get_state())
        if zr is not None: f.update_radar(zr)
        st=f.get_state(); ests.append(st); att_flags.append(attacked)
        errs.append(np.sqrt((st[0]-r['gps_x'])**2+(st[1]-r['gps_y'])**2))
        verrs.append(np.sqrt((st[3]-r['vx'])**2+(st[4]-r['vy'])**2))
    return dict(estimates=np.array(ests),ground_truth=sd[['gps_x','gps_y','gps_z']].values,
                nis=np.array(niss),errors=np.array(errs),vel_errors=np.array(verrs),
                attacked=att_flags,scene_name=sd['scene_name'].iloc[0])

def eval_all(FC,spoof_fn=None):
    res={}
    for sid in sorted(df_all['scene_id'].unique()):
        sd=df_all[df_all['scene_id']==sid].reset_index(drop=True)
        sp=spoof_fn(len(sd),seed=sid) if spoof_fn else None
        res[sid]=run_filter(FC,sd,spoof=sp)
    return res

def rmse_s(res):
    pp=[np.sqrt(np.mean(r['errors']**2)) for r in res.values()]
    vv=[np.sqrt(np.mean(r['vel_errors']**2)) for r in res.values()]
    return {'pm':np.mean(pp),'ps':np.std(pp),'vm':np.mean(vv),'vs':np.std(vv)}

KF_RES={}
print("Running KF baselines")
for fn,FC in FILTERS.items():
    KF_RES[fn]=eval_all(FC); s=rmse_s(KF_RES[fn])
    print(f"  {fn}: pos={s['pm']:.4f}±{s['ps']:.4f}m  vel={s['vm']:.4f}m/s")


# CELL 9: RL Agents + Environment

class ReplayBuf:
    def __init__(s,c=50000): s.b=deque(maxlen=c)
    def push(s,*a): s.b.append(a)
    def sample(s,n): b=random.sample(s.b,n); return [np.array(x) for x in zip(*b)]
    def __len__(s): return len(s.b)

class SpoofAttack:
    def __init__(s,N,sf=.3,ef=.7,off=(5.,2.5,0.),ramp=.1,jit=.3,seed=0):
        s.s=int(N*sf); s.e=int(N*ef); s.mx=np.array(off); s.rf=ramp; s.jit=jit; s.rng=np.random.RandomState(seed)
    def apply(s,k,gps):
        if k<s.s or k>s.e: return False,gps.copy()
        w=s.e-s.s; rl=max(1,int(w*s.rf)); p=k-s.s
        if p<rl: sc=p/rl
        elif p>w-rl: sc=(w-p)/rl
        else: sc=1.
        return True,gps+s.mx*sc+s.rng.randn(3)*s.jit*sc

class FilterEnv:
    def __init__(s,sd,FC,spoof_prob=0.):
        s.sd=sd.reset_index(drop=True); s.n=len(s.sd); s.FC=FC; s.sp_prob=spoof_prob
    def reset(s):
        s.i=0; s.pnis=0.; s.pa=np.zeros(3); s.filt=s.FC()
        r=s.sd.iloc[0]; s.filt.state=np.array([r['gps_x'],r['gps_y'],r['gps_z'],0,0,0],dtype=float)
        s.spoof=SpoofAttack(s.n,seed=np.random.randint(10000)) if np.random.rand()<s.sp_prob else None
        s.log=[]; return s._obs(False)
    def _obs(s,att):
        r=s.sd.iloc[s.i]; st=s.filt.get_state()
        return np.clip(np.array([st[0]-r['gps_x'],st[1]-r['gps_y'],st[3]-r['vx'],st[4]-r['vy'],
            s.pnis,r['ax'],r['ay'],r['radar_vel_mean'],r['radar_count'],
            np.sqrt(r['vx']**2+r['vy']**2),float(att)],dtype=np.float32),-100,100)
    def step(s,action):
        action=np.clip(action,-1,1); sc=0.15+(action+1)*2.925; s.filt.set_noise(*sc)
        s.i+=1
        if s.i>=s.n: return np.zeros(11,np.float32),0.,True,{}
        r=s.sd.iloc[s.i]; s.filt.predict(r['ax'],r['ay'],r['az'],r['dt'])
        z=np.array([r['gps_x'],r['gps_y'],r['gps_z']],dtype=float); att=False
        if s.spoof: att,z=s.spoof.apply(s.i,z)
        _,nis=s.filt.update_gps(z); s.pnis=nis
        zr=radar_vel_meas(r,s.filt.get_state())
        if zr is not None: s.filt.update_radar(zr)
        st=s.filt.get_state()
        pe=np.sqrt((st[0]-r['gps_x'])**2+(st[1]-r['gps_y'])**2)
        ve=np.sqrt((st[3]-r['vx'])**2+(st[4]-r['vy'])**2)
        rew=-pe-.4*ve+(.5 if nis<7.815 else 0)-.03*float(np.sum((action-s.pa)**2))
        s.pa=action.copy(); s.log.append(dict(step=s.i,nis=nis,attacked=att,pos_err=pe))
        return s._obs(att),rew,s.i>=s.n-1,{'pos_err':pe,'vel_err':ve,'nis':nis,'attacked':att}

# TD3
class QN(nn.Module):
    def __init__(s,sd,ad,h=256): super().__init__(); s.f1=nn.Linear(sd+ad,h); s.f2=nn.Linear(h,h); s.f3=nn.Linear(h,1)
    def forward(s,st,a): return s.f3(TF.relu(s.f2(TF.relu(s.f1(torch.cat([st,a],-1))))))
class TD3Pi(nn.Module):
    def __init__(s,sd,ad,h=256): super().__init__(); s.f1=nn.Linear(sd,h); s.f2=nn.Linear(h,h); s.o=nn.Linear(h,ad)
    def forward(s,x): return torch.tanh(s.o(TF.relu(s.f2(TF.relu(s.f1(x))))))
class TD3Agent:
    def __init__(s,sd,ad=3,lr=3e-4,g=.99,tau=.005):
        s.dv=torch.device('cuda' if torch.cuda.is_available() else 'cpu'); s.ad=ad
        s.ac=TD3Pi(sd,ad).to(s.dv); s.act_=copy.deepcopy(s.ac); s.aco=optim.Adam(s.ac.parameters(),lr=lr)
        s.q1=QN(sd,ad).to(s.dv); s.q2=QN(sd,ad).to(s.dv); s.q1t=copy.deepcopy(s.q1); s.q2t=copy.deepcopy(s.q2)
        s.qo1=optim.Adam(s.q1.parameters(),lr=lr); s.qo2=optim.Adam(s.q2.parameters(),lr=lr)
        s.g=g; s.tau=tau; s.uc=0; s.en=.3; s.buf=ReplayBuf()
    def act(s,st,ev=False):
        t=torch.FloatTensor(st).unsqueeze(0).to(s.dv); a=s.ac(t).detach().cpu().numpy()[0]
        if not ev: a=np.clip(a+np.random.normal(0,s.en,s.ad),-1,1)
        return a
    def update(s):
        if len(s.buf)<64: return
        st,at,rt,nst,dt=s.buf.sample(64); st=torch.FloatTensor(st).to(s.dv); at=torch.FloatTensor(at).to(s.dv)
        rt=torch.FloatTensor(rt).unsqueeze(1).to(s.dv); nst=torch.FloatTensor(nst).to(s.dv); dt=torch.FloatTensor(dt).unsqueeze(1).to(s.dv)
        with torch.no_grad():
            n=(torch.randn_like(at)*.2).clamp(-.5,.5); na=(s.act_(nst)+n).clamp(-1,1)
            qt=rt+s.g*(1-dt)*torch.min(s.q1t(nst,na),s.q2t(nst,na))
        for q,o in [(s.q1,s.qo1),(s.q2,s.qo2)]: l=TF.mse_loss(q(st,at),qt); o.zero_grad(); l.backward(); o.step()
        s.uc+=1
        if s.uc%2==0:
            pl=-s.q1(st,s.ac(st)).mean(); s.aco.zero_grad(); pl.backward(); s.aco.step()
            for tp,p in zip(s.act_.parameters(),s.ac.parameters()): tp.data.copy_(s.tau*p.data+(1-s.tau)*tp.data)
            for tp,p in zip(s.q1t.parameters(),s.q1.parameters()): tp.data.copy_(s.tau*p.data+(1-s.tau)*tp.data)
            for tp,p in zip(s.q2t.parameters(),s.q2.parameters()): tp.data.copy_(s.tau*p.data+(1-s.tau)*tp.data)

# SAC
class SACPi(nn.Module):
    def __init__(s,sd,ad,h=256): super().__init__(); s.f1=nn.Linear(sd,h); s.f2=nn.Linear(h,h); s.mu=nn.Linear(h,ad); s.ls=nn.Linear(h,ad)
    def forward(s,x): x=TF.relu(s.f2(TF.relu(s.f1(x)))); return s.mu(x),s.ls(x).clamp(-20,2)
    def sample(s,x): m,l=s.forward(x); std=l.exp(); d=torch.distributions.Normal(m,std); z=d.rsample(); a=torch.tanh(z); return a,(d.log_prob(z)-torch.log(1-a**2+1e-6)).sum(-1,keepdim=True)
class SACAgent:
    def __init__(s,sd,ad=3,lr=3e-4,g=.99,tau=.005):
        s.dv=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        s.pi=SACPi(sd,ad).to(s.dv); s.q1=QN(sd,ad).to(s.dv); s.q2=QN(sd,ad).to(s.dv)
        s.q1t=copy.deepcopy(s.q1); s.q2t=copy.deepcopy(s.q2)
        s.po=optim.Adam(s.pi.parameters(),lr=lr); s.qo1=optim.Adam(s.q1.parameters(),lr=lr); s.qo2=optim.Adam(s.q2.parameters(),lr=lr)
        s.la=torch.zeros(1,requires_grad=True,device=s.dv); s.ao=optim.Adam([s.la],lr=lr)
        s.te=-ad; s.g=g; s.tau=tau; s.buf=ReplayBuf()
    @property
    def alpha(s): return s.la.exp()
    def act(s,st,ev=False):
        t=torch.FloatTensor(st).unsqueeze(0).to(s.dv)
        if ev: m,_=s.pi(t); return torch.tanh(m).detach().cpu().numpy()[0]
        a,_=s.pi.sample(t); return a.detach().cpu().numpy()[0]
    def update(s):
        if len(s.buf)<64: return
        st,at,rt,nst,dt=s.buf.sample(64); st=torch.FloatTensor(st).to(s.dv); at=torch.FloatTensor(at).to(s.dv)
        rt=torch.FloatTensor(rt).unsqueeze(1).to(s.dv); nst=torch.FloatTensor(nst).to(s.dv); dt=torch.FloatTensor(dt).unsqueeze(1).to(s.dv)
        with torch.no_grad(): na,nl=s.pi.sample(nst); qn=torch.min(s.q1t(nst,na),s.q2t(nst,na))-s.alpha*nl; qt=rt+s.g*(1-dt)*qn
        for q,o in [(s.q1,s.qo1),(s.q2,s.qo2)]: l=TF.mse_loss(q(st,at),qt); o.zero_grad(); l.backward(); o.step()
        na2,lp2=s.pi.sample(st); pl=(s.alpha*lp2-torch.min(s.q1(st,na2),s.q2(st,na2))).mean()
        s.po.zero_grad(); pl.backward(); s.po.step()
        al=-(s.la*(lp2+s.te).detach()).mean(); s.ao.zero_grad(); al.backward(); s.ao.step()
        for tp,p in zip(s.q1t.parameters(),s.q1.parameters()): tp.data.copy_(s.tau*p.data+(1-s.tau)*tp.data)
        for tp,p in zip(s.q2t.parameters(),s.q2.parameters()): tp.data.copy_(s.tau*p.data+(1-s.tau)*tp.data)

# PPO
class PPONet(nn.Module):
    def __init__(s,sd,ad,h=256): super().__init__(); s.sh=nn.Sequential(nn.Linear(sd,h),nn.ReLU(),nn.Linear(h,h),nn.ReLU()); s.mu=nn.Linear(h,ad); s.ls=nn.Parameter(torch.zeros(ad)); s.v=nn.Linear(h,1)
    def forward(s,x): f=s.sh(x); return torch.tanh(s.mu(f)),s.ls,s.v(f)
class PPOAgent:
    def __init__(s,sd,ad=3,lr=3e-4,g=.99,gae=.95,cl=.2,ep=10):
        s.dv=torch.device('cuda' if torch.cuda.is_available() else 'cpu'); s.ad=ad
        s.net=PPONet(sd,ad).to(s.dv); s.opt=optim.Adam(s.net.parameters(),lr=lr)
        s.g=g; s.gae=gae; s.cl=cl; s.ep=ep; s._r()
    def _r(s): s.S,s.A,s.R,s.LP,s.V,s.D=[],[],[],[],[],[]
    def act(s,st,ev=False):
        t=torch.FloatTensor(st).unsqueeze(0).to(s.dv); m,l,v=s.net(t)
        if ev: return m.detach().cpu().numpy()[0]
        std=l.exp().clamp(.01,1.); d=torch.distributions.Normal(m,std); a=d.sample().clamp(-1,1)
        s.LP.append(d.log_prob(a).sum(-1).detach().cpu()); s.V.append(v.item())
        return a.detach().cpu().numpy()[0]
    def store(s,st,a,r,d): s.S.append(st); s.A.append(a); s.R.append(r); s.D.append(d)
    def update(s):
        if len(s.S)<32: return
        vs=s.V+[0.]; adv=[]; ret=[]; ga=0
        for t in reversed(range(len(s.R))): d=s.R[t]+s.g*vs[t+1]*(1-s.D[t])-vs[t]; ga=d+s.g*s.gae*(1-s.D[t])*ga; adv.insert(0,ga); ret.insert(0,ga+vs[t])
        st=torch.FloatTensor(np.array(s.S)).to(s.dv); at=torch.FloatTensor(np.array(s.A)).to(s.dv)
        olp=torch.stack(s.LP).to(s.dv); advt=torch.FloatTensor(adv).to(s.dv); rett=torch.FloatTensor(ret).to(s.dv)
        if len(advt)>1: advt=(advt-advt.mean())/(advt.std()+1e-8)
        N=len(st); mb=max(1,N//4)
        for _ in range(s.ep):
            idx=torch.randperm(N)
            for start in range(0,N,mb):
                b=idx[start:start+mb]; m,l,vp=s.net(st[b]); std=l.exp().clamp(.01,1.)
                d=torch.distributions.Normal(m,std); nlp=d.log_prob(at[b]).sum(-1)
                r=(nlp-olp[b]).exp()
                loss=-torch.min(r*advt[b],torch.clamp(r,1-s.cl,1+s.cl)*advt[b]).mean()+.5*TF.mse_loss(vp.squeeze(-1),rett[b])-.01*d.entropy().sum(-1).mean()
                s.opt.zero_grad(); loss.backward(); nn.utils.clip_grad_norm_(s.net.parameters(),.5); s.opt.step()
        s._r()

# Ensemble
class EnsembleAgent:
    def __init__(s,agents): s.agents=agents
    def act(s,state,ev=True): return np.median([a.act(state,ev=ev) for _,a in s.agents],axis=0)

AGENTS={'TD3':TD3Agent,'SAC':SACAgent,'PPO':PPOAgent}
print("RL agents TD3, SAC, PPO, Ensemble")


# CELL 10: Training

EPISODES=200

def set_seeds(seed=42): np.random.seed(seed); random.seed(seed); torch.manual_seed(seed)

def train_agent(FC,AC,aname,episodes=EPISODES,seed=42,spoof_prob=0.):
    set_seeds(seed)
    train_dfs=[df_all[df_all['scene_id']==s].reset_index(drop=True) for s in train_scenes_ids if len(df_all[df_all['scene_id']==s])>5]
    agent=AC(11,ad=3); rets,errs=[],[]
    for ep in range(episodes):
        env=FilterEnv(train_dfs[ep%len(train_dfs)],FC,spoof_prob=spoof_prob)
        s=env.reset(); tr,se=0.,[]
        while True:
            a=agent.act(s); ns,r,done,info=env.step(a)
            if aname=='PPO': agent.store(s,a,r,float(done))
            else: agent.buf.push(s,a,r,ns,float(done)); agent.update()
            tr+=r
            if 'pos_err' in info: se.append(info['pos_err'])
            s=ns
            if done: break
        if aname=='PPO': agent.update()
        rets.append(tr); errs.append(np.mean(se) if se else 0.)
        if aname=='TD3': agent.en=max(.03,agent.en*.995)
        if (ep+1)%50==0: print(f"  {aname} ep {ep+1}/{episodes} ret={np.mean(rets[-50:]):.1f} err={np.mean(errs[-50:]):.3f}m")
    return agent,{'returns':rets,'errors':errs}

def eval_agent(FC,agent,aname,spoof_fn=None):
    res={}
    for sid in sorted(df_all['scene_id'].unique()):
        sd=df_all[df_all['scene_id']==sid].reset_index(drop=True)
        sp=spoof_fn(len(sd),seed=sid) if spoof_fn else None
        env=FilterEnv(sd,FC); env.spoof=sp; s=env.reset()
        ests,errs,verrs,niss,att=[env.filt.get_state()],[0.],[0.],[0.],[False]
        while True:
            a=agent.act(s,ev=True); ns,_,done,info=env.step(a)
            ests.append(env.filt.get_state())
            errs.append(info.get('pos_err',0.)); verrs.append(info.get('vel_err',0.))
            niss.append(info.get('nis',0.)); att.append(info.get('attacked',False))
            s=ns
            if done: break
        res[sid]=dict(estimates=np.array(ests),ground_truth=sd[['gps_x','gps_y','gps_z']].values,
                       errors=np.array(errs),vel_errors=np.array(verrs),nis=np.array(niss),
                       attacked=att,scene_name=sd['scene_name'].iloc[0])
    return res

print(f"Training functions. EPISODES={EPISODES}")


# CELL 11: Train ALL Sensor Combinations and KF, RL, Evaluate ALL Under Clean & Spoofed

ALL = {}; LOGS = {}; TRAINED = {}
ALL.update(KF_RES)  # EKF, UKF, CKF baselines (clean)

#  Train filter and RL combinations

print("=" * 60)
print("  STEP 1: TRAINING 9 FILTER × RL COMBINATIONS")
print("=" * 60)

for fn, FC in FILTERS.items():
    for aname, AC in AGENTS.items():
        key = f'{fn}+{aname}'
        print(f"\n--- {key} ---")
        agent, log = train_agent(FC, AC, aname, episodes=EPISODES, seed=42)
        TRAINED[(fn, aname)] = agent
        LOGS[key] = log
        ALL[key] = eval_agent(FC, agent, aname)
        s = rmse_s(ALL[key])
        print(f"  {key}: pos={s['pm']:.4f}m  vel={s['vm']:.4f}m/s")


# Building Ensemble for each filter

print("\n" + "=" * 60)
print(" ENSEMBLE RL (TD3+SAC+PPO MEDIAN)")
print("=" * 60)

for fn, FC in FILTERS.items():
    ens_key = f'{fn}+Ensemble'
    ens = EnsembleAgent([(n, TRAINED[(fn, n)]) for n in ['TD3', 'SAC', 'PPO']])
    TRAINED[(fn, 'Ensemble')] = ens
    ALL[ens_key] = eval_agent(FC, ens, 'Ensemble')
    s = rmse_s(ALL[ens_key])
    print(f"  {ens_key}: pos={s['pm']:.4f}m  vel={s['vm']:.4f}m/s")

#  STEP 3: Spoof-aware TD3 training

print("\n" + "=" * 60)
print(" SPOOF AWARE TD3 TRAINING")
print("=" * 60)

for fn, FC in FILTERS.items():
    sa_key = f'{fn}+TD3-SA'
    print(f"\n--- {sa_key} (trained with 70% spoof exposure) ---")
    sa_agent, sa_log = train_agent(FC, TD3Agent, 'TD3', episodes=EPISODES, seed=123, spoof_prob=0.7)
    TRAINED[(fn, 'TD3-SA')] = sa_agent
    LOGS[sa_key] = sa_log
    # Evaluate on clean
    ALL[f'{fn}+TD3-SA(clean)'] = eval_agent(FC, sa_agent, 'TD3')
    s = rmse_s(ALL[f'{fn}+TD3-SA(clean)'])
    print(f"  {fn}+TD3-SA clean: pos={s['pm']:.4f}m")

# Build spoof-aware ensemble for each filter
print("\n Spoof-Aware Ensembles")
for fn, FC in FILTERS.items():
    sa_ens = EnsembleAgent([('TD3', TRAINED[(fn, 'TD3-SA')]),
                             ('SAC', TRAINED[(fn, 'SAC')]),
                             ('PPO', TRAINED[(fn, 'PPO')])])
    TRAINED[(fn, 'SA-Ensemble')] = sa_ens
    ALL[f'{fn}+SA-Ensemble(clean)'] = eval_agent(FC, sa_ens, 'Ensemble')
    s = rmse_s(ALL[f'{fn}+SA-Ensemble(clean)'])
    print(f"  {fn}+SA-Ensemble clean: pos={s['pm']:.4f}m")


#  EVALUATING EVERYTHING UNDER SPOOFING

print("\n" + "=" * 60)
print(" EVALUATE ALL METHODS UNDER GPS SPOOFING")
print("=" * 60)

# This function is to test every single method under spoofed GPS
spoof_methods_to_test = {}

# Filter baselines under spoofing
for fn, FC in FILTERS.items():
    key = f'{fn}(spoofed)'
    spoof_methods_to_test[key] = (FC, None, fn)  # no agent, just filter

# All RL Combinations under spoofing
for fn, FC in FILTERS.items():
    for aname in ['TD3', 'SAC', 'PPO']:
        key = f'{fn}+{aname}(spoofed)'
        spoof_methods_to_test[key] = (FC, TRAINED[(fn, aname)], aname)

# All 3 ensembles under spoofing
for fn, FC in FILTERS.items():
    key = f'{fn}+Ensemble(spoofed)'
    spoof_methods_to_test[key] = (FC, TRAINED[(fn, 'Ensemble')], 'Ensemble')

# All 3 spoof-aware TD3 under spoofing
for fn, FC in FILTERS.items():
    key = f'{fn}+TD3-SA(spoofed)'
    spoof_methods_to_test[key] = (FC, TRAINED[(fn, 'TD3-SA')], 'TD3')

# All 3 spoof-aware ensembles under spoofing
for fn, FC in FILTERS.items():
    key = f'{fn}+SA-Ensemble(spoofed)'
    spoof_methods_to_test[key] = (FC, TRAINED[(fn, 'SA-Ensemble')], 'Ensemble')

# Running all spoofed evaluations
for key, (FC, agent, aname) in spoof_methods_to_test.items():
    if agent is None:
        # Filter-only under spoof
        ALL[key] = eval_all(FC, spoof_fn=SpoofAttack)
    else:
        ALL[key] = eval_agent(FC, agent, aname, spoof_fn=SpoofAttack)
    s = rmse_s(ALL[key])
    print(f"  {key:35s}  pos={s['pm']:.4f}m")


#  SUMMARY TABLE

print("\n" + "=" * 70)
print("RESULTS: ALL METHODS, CLEAN AND SPOOFED")
print("=" * 70)

ekf_r = rmse_s(ALL['EKF'])['pm']

print("\n CLEAN GPS ")
clean_keys = [k for k in ALL if 'spoofed' not in k.lower() and 'spoof' not in k.lower()]
for k in sorted(clean_keys, key=lambda x: rmse_s(ALL[x])['pm']):
    s = rmse_s(ALL[k])
    imp = (ekf_r - s['pm']) / ekf_r * 100
    print(f"  {k:35s}  pos={s['pm']:.4f}m  vel={s['vm']:.4f}m/s  ({imp:+.1f}%)")

# Spoofed results
print("\n UNDER GPS SPOOFING ")
spoof_keys = [k for k in ALL if 'spoofed' in k.lower() or 'spoof' in k.lower()]
for k in sorted(spoof_keys, key=lambda x: rmse_s(ALL[x])['pm']):
    s = rmse_s(ALL[k])
    print(f"  {k:35s}  pos={s['pm']:.4f}m  vel={s['vm']:.4f}m/s")

print(f"\nTotal methods evaluated: {len(ALL)}")
print(f"  Clean: {len(clean_keys)}")
print(f"  Spoofed: {len(spoof_keys)}")


# CELL 12: Organized Trajectory Comparisons


import matplotlib.gridspec as gridspec
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.patheffects as pe

try:
    from mpl_toolkits.axes_grid1.inset_locator import inset_axes
except:
    pass

plt.rcParams['figure.facecolor'] = 'white'
plt.rcParams['axes.facecolor'] = '#FCFCFC'
plt.rcParams['axes.edgecolor'] = '#666666'
plt.rcParams['axes.linewidth'] = 0.8
plt.rcParams['grid.alpha'] = 0.25
plt.rcParams['grid.linestyle'] = '--'
plt.rcParams['font.size'] = 11
plt.rcParams['axes.titleweight'] = 'bold'
plt.rcParams['axes.labelweight'] = 'bold'
plt.rcParams['legend.framealpha'] = 0.95


def safe_scene_list():
    if 'EKF' in KF_RES:
        return sorted(KF_RES['EKF'].keys())
    return []

def scene_rmse(method_key, sid):
    return np.sqrt(np.mean(ALL[method_key][sid]['errors'] ** 2))

def get_method_color(name):
    if 'TD3' in name:
        return C['td3']
    elif 'SAC' in name:
        return C['sac']
    elif 'PPO' in name:
        return C['ppo']
    elif 'Ensemble' in name:
        return '#E74C3C'
    elif 'SA' in name:
        return C['defense']
    else:
        base = name.split('+')[0].replace('(spoofed)', '').replace('(clean)', '').strip()
        return C.get(base.lower(), C['accent'])

def short_name(n):
    return (n.replace('UKF+', 'U+')
             .replace('EKF+', 'E+')
             .replace('CKF+', 'C+')
             .replace('+Ensemble', '+Ens')
             .replace('(spoofed)', '(sp)')
             .replace('(clean)', '(cl)'))

def style_method_line(ax, x, y, color, label, lw=2.0, ls='-', alpha=0.95, z=3):
    line, = ax.plot(x, y, color=color, linewidth=lw, linestyle=ls,
                    alpha=alpha, label=label, zorder=z)
    line.set_path_effects([
        pe.Stroke(linewidth=lw + 1.2, foreground='white', alpha=0.22),
        pe.Normal()
    ])
    return line

def add_start_end(ax, traj, s1=80, s2=90, add_labels=True):
    ax.scatter(traj[0, 0], traj[0, 1], c='limegreen', marker='o', s=s1,
               edgecolors='black', zorder=8, label='Start' if add_labels else None)
    ax.scatter(traj[-1, 0], traj[-1, 1], c='red', marker='X', s=s2,
               edgecolors='black', zorder=8, label='End' if add_labels else None)

def best_clean_methods(all_rmse, topn=4):
    ranked_local = sorted(all_rmse.items(), key=lambda x: x[1]['pos'])
    return [k for k, _ in ranked_local[:topn]]

def maybe_equal_axis(ax, x, y, pad_ratio=0.08):
    x = np.asarray(x)
    y = np.asarray(y)
    xmin, xmax = np.min(x), np.max(x)
    ymin, ymax = np.min(y), np.max(y)
    xr = xmax - xmin
    yr = ymax - ymin
    if xr == 0: xr = 1.0
    if yr == 0: yr = 1.0
    pad_x = xr * pad_ratio
    pad_y = yr * pad_ratio
    ax.set_xlim(xmin - pad_x, xmax + pad_x)
    ax.set_ylim(ymin - pad_y, ymax + pad_y)
    ax.set_aspect('equal', adjustable='box')

def valid_scene_methods(methods, sid):
    return [m for m in methods if m in ALL and sid in ALL[m]]

sids = safe_scene_list()
if len(sids) == 0:
    raise ValueError("No scene IDs found in KF_RES['EKF'].")

sid0 = sids[0]
plot_sids = sids[:3]
ekf_rmse = rmse_s(ALL['EKF'])['pm'] if 'EKF' in ALL else 1.0

fig, axes = plt.subplots(1, 3, figsize=(22, 7))
for ai, sid in enumerate(plot_sids):
    ax = axes[ai]
    gt = ALL['EKF'][sid]['ground_truth']

    style_method_line(ax, gt[:, 0], gt[:, 1], C['gt'], 'Ground Truth',
                      lw=4.0, ls='-', alpha=1.0, z=10)
    add_start_end(ax, gt, add_labels=(ai == 0))

    for fn, col, ls in [('EKF', C['ekf'], '--'), ('UKF', C['ukf'], '-.'), ('CKF', C['ckf'], ':')]:
        if fn in ALL and sid in ALL[fn]:
            e = ALL[fn][sid]['estimates']
            r = scene_rmse(fn, sid)
            style_method_line(ax, e[:, 0], e[:, 1], col,
                              f'{fn} ({r:.3f}m)', lw=2.2, ls=ls, alpha=0.88)

    ax.set_title(f'Scene {sid}', fontsize=12, fontweight='bold')
    ax.set_xlabel('X Position (m)')
    ax.set_ylabel('Y Position (m)')
    ax.grid(True)
    maybe_equal_axis(ax, gt[:, 0], gt[:, 1])
    ax.legend(fontsize=8, loc='best')

plt.suptitle('Filter Comparison: EKF vs UKF vs CKF\n'
             'Representative trajectory tracking performance',
             fontsize=14, fontweight='bold', y=1.03)
plt.tight_layout()
plt.savefig('fig05_filter_trajectories.png', dpi=300, bbox_inches='tight')
plt.show()
print("Filter trajectory comparison")


fig, axes = plt.subplots(1, 3, figsize=(22, 7))
rl_styles = {
    'UKF': (C['ukf'], '--', 1.8, 'UKF (no RL)'),
    'UKF+TD3': (C['td3'], '-', 2.4, 'UKF+TD3'),
    'UKF+SAC': (C['sac'], '-', 2.2, 'UKF+SAC'),
    'UKF+PPO': (C['ppo'], '-', 2.2, 'UKF+PPO'),
    'UKF+Ensemble': ('#E74C3C', '-', 3.0, 'UKF+Ensemble'),
}

for ai, sid in enumerate(plot_sids):
    ax = axes[ai]
    gt = ALL['EKF'][sid]['ground_truth']

    style_method_line(ax, gt[:, 0], gt[:, 1], C['gt'], 'Ground Truth',
                      lw=4.0, ls='-', alpha=1.0, z=10)
    add_start_end(ax, gt, add_labels=False)

    for mn, (col, ls, lw, lab) in rl_styles.items():
        if mn in ALL and sid in ALL[mn]:
            e = ALL[mn][sid]['estimates']
            r = scene_rmse(mn, sid)
            style_method_line(ax, e[:, 0], e[:, 1], col,
                              f'{lab} ({r:.3f}m)', lw=lw, ls=ls,
                              alpha=0.92 if 'Ensemble' in mn else 0.85)

    ax.set_title(f'Scene {sid}', fontsize=12, fontweight='bold')
    ax.set_xlabel('X (m)')
    ax.set_ylabel('Y (m)')
    ax.grid(True)
    maybe_equal_axis(ax, gt[:, 0], gt[:, 1])
    if ai == 0:
        ax.legend(fontsize=7, loc='best')

plt.suptitle('RL Algorithm Comparison on UKF\n'
             'Baseline UKF versus RL-tuned variants',
             fontsize=14, fontweight='bold', y=1.03)
plt.tight_layout()
plt.savefig('fig06_rl_trajectories.png', dpi=300, bbox_inches='tight')
plt.show()
print("RL trajectory comparison")


fig, axes = plt.subplots(1, 3, figsize=(22, 7))

for ai, (fn, FC) in enumerate(FILTERS.items()):
    ax = axes[ai]
    if fn not in ALL or sid0 not in ALL[fn]:
        ax.axis('off')
        continue

    gt = ALL[fn][sid0]['ground_truth']
    style_method_line(ax, gt[:, 0], gt[:, 1], C['gt'], 'Ground Truth',
                      lw=4.0, ls='-', alpha=1.0, z=10)
    add_start_end(ax, gt, add_labels=False)

    e = ALL[fn][sid0]['estimates']
    r = scene_rmse(fn, sid0)
    style_method_line(ax, e[:, 0], e[:, 1], C[fn.lower()],
                      f'{fn} baseline ({r:.3f}m)', lw=1.8, ls='--', alpha=0.75)

    for aname, col in [('TD3', C['td3']), ('SAC', C['sac']), ('PPO', C['ppo']), ('Ensemble', '#E74C3C')]:
        key = f'{fn}+{aname}'
        if key in ALL and sid0 in ALL[key]:
            e = ALL[key][sid0]['estimates']
            r = scene_rmse(key, sid0)
            style_method_line(ax, e[:, 0], e[:, 1], col,
                              f'+{aname} ({r:.3f}m)',
                              lw=2.8 if aname == 'Ensemble' else 2.1,
                              ls='-', alpha=0.9)

    ax.set_title(f'{fn} Filter Family', fontsize=12, fontweight='bold')
    ax.set_xlabel('X (m)')
    ax.set_ylabel('Y (m)')
    ax.grid(True)
    maybe_equal_axis(ax, gt[:, 0], gt[:, 1])
    ax.legend(fontsize=7, loc='best')

plt.suptitle(f'Each Filter Family with RL Variants (Scene {sid0})\n'
             'Dashed = filter only | Solid = RL tuned',
             fontsize=14, fontweight='bold', y=1.03)
plt.tight_layout()
plt.savefig('fig07_filter_families.png', dpi=300, bbox_inches='tight')
plt.show()
print("Filter trajectories")


fig, axes = plt.subplots(1, 3, figsize=(22, 7))
gt = ALL['EKF'][sid0]['ground_truth']

# Filter baselines under spoof
ax = axes[0]
style_method_line(ax, gt[:, 0], gt[:, 1], C['gt'], 'Ground Truth',
                  lw=4.0, ls='-', alpha=1.0, z=10)
add_start_end(ax, gt, add_labels=False)

for fn, col, ls in [('EKF', C['ekf'], '-'), ('UKF', C['ukf'], '-.'), ('CKF', C['ckf'], ':')]:
    spk = f'{fn}(spoofed)'
    if fn in ALL and sid0 in ALL[fn]:
        r_c = scene_rmse(fn, sid0)
        e = ALL[fn][sid0]['estimates']
        style_method_line(ax, e[:, 0], e[:, 1], col,
                          f'{fn} clean ({r_c:.2f}m)', lw=1.8, ls=ls, alpha=0.55)
    if spk in ALL and sid0 in ALL[spk]:
        r_s = scene_rmse(spk, sid0)
        e = ALL[spk][sid0]['estimates']
        style_method_line(ax, e[:, 0], e[:, 1], col,
                          f'{fn} spoofed ({r_s:.2f}m)', lw=2.8, ls='-', alpha=0.92)

ax.set_title('Filters Under Spoofing\n(dashed=clean, solid=spoofed)', fontsize=11, fontweight='bold')
ax.set_xlabel('X (m)')
ax.set_ylabel('Y (m)')
ax.grid(True)
maybe_equal_axis(ax, gt[:, 0], gt[:, 1])
ax.legend(fontsize=6, loc='best')

ax = axes[1]
style_method_line(ax, gt[:, 0], gt[:, 1], C['gt'], 'Ground Truth',
                  lw=4.0, ls='-', alpha=1.0, z=10)
add_start_end(ax, gt, add_labels=False)

td3_methods = [
    ('UKF+TD3', 'TD3 clean', C['td3'], '-', 2.4),
    ('UKF+TD3(spoofed)', 'TD3 spoofed', C['attack'], '--', 2.2),
    ('UKF+TD3-SA(clean)', 'SA-TD3 clean', C['defense'], '-', 2.4),
    ('UKF+TD3-SA(spoofed)', 'SA-TD3 spoofed', C['accent'], '-.', 2.6),
]
for key, lab, col, ls, lw in td3_methods:
    if key in ALL and sid0 in ALL[key]:
        e = ALL[key][sid0]['estimates']
        r = scene_rmse(key, sid0)
        style_method_line(ax, e[:, 0], e[:, 1], col, f'{lab} ({r:.2f}m)',
                          lw=lw, ls=ls, alpha=0.9)

ax.set_title('TD3: Naive vs Spoof-Aware', fontsize=11, fontweight='bold')
ax.set_xlabel('X (m)')
ax.set_ylabel('Y (m)')
ax.grid(True)
maybe_equal_axis(ax, gt[:, 0], gt[:, 1])
ax.legend(fontsize=7, loc='best')

ax = axes[2]
style_method_line(ax, gt[:, 0], gt[:, 1], C['gt'], 'Ground Truth',
                  lw=4.0, ls='-', alpha=1.0, z=10)
add_start_end(ax, gt, add_labels=False)

ens_methods = [
    ('UKF+Ensemble', 'Ensemble clean', '#E74C3C', '-', 2.8),
    ('UKF+Ensemble(spoofed)', 'Ensemble spoofed', C['attack'], '--', 2.2),
    ('UKF+SA-Ensemble(clean)', 'SA-Ensemble clean', C['defense'], '-', 2.8),
    ('UKF+SA-Ensemble(spoofed)', 'SA-Ensemble spoofed', C['accent'], '-.', 2.6),
]
for key, lab, col, ls, lw in ens_methods:
    if key in ALL and sid0 in ALL[key]:
        e = ALL[key][sid0]['estimates']
        r = scene_rmse(key, sid0)
        style_method_line(ax, e[:, 0], e[:, 1], col, f'{lab} ({r:.2f}m)',
                          lw=lw, ls=ls, alpha=0.92)

ax.set_title('Ensemble: Naive vs Spoof-Aware', fontsize=11, fontweight='bold')
ax.set_xlabel('X (m)')
ax.set_ylabel('Y (m)')
ax.grid(True)
maybe_equal_axis(ax, gt[:, 0], gt[:, 1])
ax.legend(fontsize=7, loc='best')

plt.suptitle(f'GPS Spoofing Comparison (Scene {sid0})\n'
             'Clean, attacked, and defended trajectories',
             fontsize=14, fontweight='bold', y=1.03)
plt.tight_layout()
plt.savefig('fig08_spoofing_trajectories.png', dpi=300, bbox_inches='tight')
plt.show()
print("Spoofing trajectory comparison")

fig, axes = plt.subplots(1, 2, figsize=(18, 7))

best_methods = ['EKF', 'UKF', 'UKF+TD3', 'UKF+Ensemble']
for ai, sid in enumerate(sids[:2]):
    ax = axes[ai]
    gt = ALL['EKF'][sid]['ground_truth']

    style_method_line(ax, gt[:, 0], gt[:, 1], C['gt'], 'Ground Truth',
                      lw=4.0, ls='-', alpha=1.0, z=10)
    add_start_end(ax, gt, add_labels=(ai == 0))

    for mn in best_methods:
        if mn in ALL and sid in ALL[mn]:
            e = ALL[mn][sid]['estimates']
            r = np.sqrt(np.mean(ALL[mn][sid]['errors'] ** 2))
            col = get_method_color(mn)
            ls = '-' if mn == 'EKF' else '-.' if mn == 'UKF' else '-'
            lw = 2.0 if mn in ['EKF', 'UKF'] else 3.0
            alpha = 0.8 if mn in ['EKF', 'UKF'] else 0.95
            style_method_line(ax, e[:, 0], e[:, 1], col, f'{mn} ({r:.3f}m)',
                              lw=lw, ls=ls, alpha=alpha)

    ax.set_title(f'Scene {sid}: Best Trajectory Comparison', fontsize=13, fontweight='bold')
    ax.set_xlabel('X Position (m)', fontweight='bold')
    ax.set_ylabel('Y Position (m)', fontweight='bold')
    ax.grid(True, alpha=0.25, linestyle='-')
    maybe_equal_axis(ax, gt[:, 0], gt[:, 1])

    if ai == 0:
        ax.legend(fontsize=9, loc='best')

plt.suptitle('Best Trajectories Compared Clearly\n'
             'Ground truth, baselines, and strongest RL methods only',
             fontsize=15, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('fig09_best_trajectories_clear.png', dpi=300, bbox_inches='tight')
plt.show()
print("best trajectory comparison")


fig = plt.figure(figsize=(16, 7))
methods_3d = ['EKF', 'UKF+Ensemble']

for ai, sid in enumerate(sids[:2]):
    ax = fig.add_subplot(1, 2, ai + 1, projection='3d')
    gt = ALL['EKF'][sid]['ground_truth']

    ax.plot(gt[:, 0], gt[:, 1], np.arange(len(gt)),
            color=C['gt'], linewidth=3.5, label='Ground Truth')
    for mn in methods_3d:
        if mn in ALL and sid in ALL[mn]:
            e = ALL[mn][sid]['estimates']
            col = get_method_color(mn)
            lw = 1.8 if mn == 'EKF' else 3.0
            ls = '--' if mn == 'EKF' else '-'
            ax.plot(e[:, 0], e[:, 1], np.arange(len(e)),
                    color=col, linewidth=lw, linestyle=ls, label=mn)

    ax.view_init(elev=28, azim=-58)
    ax.set_xlabel('X (m)', fontweight='bold')
    ax.set_ylabel('Y (m)', fontweight='bold')
    ax.set_zlabel('Time', fontweight='bold')
    ax.set_title(f'Scene {sid}', fontsize=12, fontweight='bold')
    if ai == 0:
        ax.legend(fontsize=9, loc='upper left')

plt.suptitle('3D Trajectory View (Simplified to Most Important Methods)',
             fontsize=14, fontweight='bold', y=0.98)
plt.tight_layout()
plt.savefig('fig09_3d_simplified.png', dpi=300, bbox_inches='tight')
plt.show()
print("simplified 3D trajectories")

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 5))
win = 20

for aname, col, lab in [('TD3', C['td3'], 'TD3'), ('SAC', C['sac'], 'SAC'), ('PPO', C['ppo'], 'PPO')]:
    key = f'UKF+{aname}'
    if key in LOGS:
        raw = np.array(LOGS[key]['returns'])
        sm = pd.Series(raw).rolling(win, min_periods=1).mean()
        sm_std = pd.Series(raw).rolling(win, min_periods=1).std().fillna(0)
        ax1.plot(sm, color=col, linewidth=2.5, label=lab)
        ax1.fill_between(range(len(sm)), sm - sm_std, sm + sm_std, alpha=0.14, color=col)

        sm_e = pd.Series(LOGS[key]['errors']).rolling(win, min_periods=1).mean()
        ax2.plot(sm_e, color=col, linewidth=2.5, label=lab)

for sa_key, col, lab in [('UKF+TD3-SA', C['defense'], 'TD3 (Spoof-Aware)')]:
    if sa_key in LOGS:
        raw = np.array(LOGS[sa_key]['returns'])
        sm = pd.Series(raw).rolling(win, min_periods=1).mean()
        sm_std = pd.Series(raw).rolling(win, min_periods=1).std().fillna(0)
        ax1.plot(sm, color=col, linewidth=2.5, linestyle='-', label=lab)
        ax1.fill_between(range(len(sm)), sm - sm_std, sm + sm_std, alpha=0.10, color=col)

        sm_e = pd.Series(LOGS[sa_key]['errors']).rolling(win, min_periods=1).mean()
        ax2.plot(sm_e, color=col, linewidth=2.5, linestyle='-', label=lab)

ax1.set_xlabel('Episode')
ax1.set_ylabel('Return')
ax1.set_title('Training Return (Higher = Better)', fontsize=12, fontweight='bold')
ax1.grid(True)
ax1.legend(fontsize=9)

ax2.set_xlabel('Episode')
ax2.set_ylabel('Position Error (m)')
ax2.set_title('Training Error (Lower = Better)', fontsize=12, fontweight='bold')
ax2.grid(True)
ax2.legend(fontsize=9)

plt.suptitle('RL Training Convergence',
             fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('fig10_training_curves.png', dpi=300, bbox_inches='tight')
plt.show()
print("Training curves")

fig, axes = plt.subplots(2, 3, figsize=(22, 10))

filter_only = ['EKF', 'UKF', 'CKF']
best_rl_only = ['UKF+TD3', 'UKF+SAC', 'UKF+PPO', 'UKF+Ensemble']

for ai, sid in enumerate(plot_sids):
    ax = axes[0, ai]
    for mn in filter_only:
        if mn in ALL and sid in ALL[mn]:
            y = ALL[mn][sid]['errors']
            style_method_line(
                ax, np.arange(len(y)), y,
                get_method_color(mn), mn,
                lw=2.3 if mn == 'UKF' else 1.8,
                ls='--' if mn == 'EKF' else '-.' if mn == 'UKF' else ':',
                alpha=0.95
            )
    ax.set_title(f'Scene {sid} — Filter Errors', fontsize=11, fontweight='bold')
    ax.set_xlabel('Timestep')
    ax.set_ylabel('Error (m)')
    ax.grid(True)
    if ai == 0:
        ax.legend(fontsize=8)

    ax2 = axes[1, ai]
    for mn in best_rl_only:
        if mn in ALL and sid in ALL[mn]:
            y = ALL[mn][sid]['errors']
            style_method_line(
                ax2, np.arange(len(y)), y,
                get_method_color(mn), mn,
                lw=3.0 if 'Ensemble' in mn else 2.2,
                ls='-',
                alpha=0.95
            )
    ax2.set_title(f'Scene {sid} — RL-Tuned Errors', fontsize=11, fontweight='bold')
    ax2.set_xlabel('Timestep')
    ax2.set_ylabel('Error (m)')
    ax2.grid(True)
    if ai == 0:
        ax2.legend(fontsize=8)

plt.suptitle('Position Error Over Time — Separated for Clarity',
             fontsize=15, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('fig11_error_grouped_clear.png', dpi=300, bbox_inches='tight')
plt.show()
print("Grouped figures")


clean_keys = [k for k in ALL if 'spoofed' not in k.lower()]
all_rmse = {k: {'pos': rmse_s(ALL[k])['pm'], 'vel': rmse_s(ALL[k])['vm']} for k in clean_keys}
ranked = sorted(all_rmse.items(), key=lambda x: x[1]['pos'])
names_r = [r[0] for r in ranked]
vals_r = [r[1]['pos'] for r in ranked]
cols_r = [get_method_color(n) for n in names_r]

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20, 8))

for mn, rv in all_rmse.items():
    col = get_method_color(mn)
    mk = 'o' if mn in FILTERS else ('s' if 'Ensemble' in mn else '^')
    size = 220 if mn in ['EKF', 'UKF', 'CKF', 'UKF+TD3', 'UKF+Ensemble'] else 120
    ax1.scatter(rv['pos'], rv['vel'], s=size, color=col, marker=mk,
                edgecolors='black', linewidth=0.9, alpha=0.88, zorder=4)

label_methods = ['EKF', 'UKF', 'CKF'] + best_clean_methods(all_rmse, topn=5)
label_methods = list(dict.fromkeys(label_methods))

for mn in label_methods:
    if mn in all_rmse:
        x = all_rmse[mn]['pos']
        y = all_rmse[mn]['vel']
        ax1.annotate(short_name(mn), (x, y), textcoords='offset points', xytext=(6, 6),
                     fontsize=9, fontweight='bold',
                     bbox=dict(boxstyle='round,pad=0.18', fc='white', ec='none', alpha=0.75))

ax1.set_xlabel('Position RMSE (m)', fontsize=12, fontweight='bold')
ax1.set_ylabel('Velocity RMSE (m/s)', fontsize=12, fontweight='bold')
ax1.set_title('Method Landscape (Bottom-left = Best)', fontsize=13, fontweight='bold')
ax1.grid(True, alpha=0.22, linestyle='--')

xvals = np.array([v['pos'] for v in all_rmse.values()])
yvals = np.array([v['vel'] for v in all_rmse.values()])
ax1.set_xlim(0, min(max(np.percentile(xvals, 95) * 1.15, 1.0), max(xvals) * 1.02))
ax1.set_ylim(0, min(max(np.percentile(yvals, 95) * 1.15, 1.0), max(yvals) * 1.02))

top_show = min(12, len(ranked))
top_ranked = ranked[:top_show]
top_names = [n for n, _ in top_ranked]
top_pos_vals = [v['pos'] for _, v in top_ranked]
top_cols = [get_method_color(n) for n in top_names]

ax2.barh(range(top_show), top_pos_vals, color=top_cols,
         edgecolor='white', height=0.68, alpha=0.9)
ax2.set_yticks(range(top_show))
ax2.set_yticklabels([short_name(n) for n in top_names], fontsize=10)
ax2.set_xlabel('Position RMSE (m)', fontweight='bold')
ax2.set_title('Top Methods Ranked (Lower = Better)', fontsize=13, fontweight='bold')
ax2.invert_yaxis()
ax2.grid(True, axis='x', alpha=0.2, linestyle='-')

for i, (n, v) in enumerate(top_ranked):
    imp = (ekf_rmse - v['pos']) / ekf_rmse * 100
    ax2.text(v['pos'] + 0.01, i, f'{v["pos"]:.3f}m ({imp:+.0f}%)',
             va='center', fontsize=8.5, fontweight='bold')

plt.suptitle('State Estimation Performance — Cleaner Comparison',
             fontsize=15, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('fig12_rmse_comparison_clear.png', dpi=300, bbox_inches='tight')
plt.show()
print("RMSE comparison")

fig, ax = plt.subplots(figsize=(20, 8))

pairs = []
for k in ALL:
    if 'spoofed' in k.lower():
        clean_k = k.replace('(spoofed)', '').replace('(spoofed', '').strip()
        if clean_k.endswith('+'):
            clean_k = clean_k[:-1]
        if clean_k in ALL:
            pairs.append((clean_k, k))
        else:
            base = k.split('(')[0].strip()
            if base in ALL:
                pairs.append((base, k))

pairs = list(dict.fromkeys(pairs))
pairs.sort(key=lambda x: rmse_s(ALL[x[0]])['pm'])

if pairs:
    x = np.arange(len(pairs))
    w = 0.35
    clean_vals = [rmse_s(ALL[ck])['pm'] for ck, _ in pairs]
    spoof_vals = [rmse_s(ALL[sk])['pm'] for _, sk in pairs]

    ax.bar(x - w / 2, clean_vals, w, label='Clean GPS',
           color=C['td3'], edgecolor='white', alpha=0.88)
    ax.bar(x + w / 2, spoof_vals, w, label='Under GPS Spoofing',
           color=C['attack'], edgecolor='white', alpha=0.88)

    ax.set_xticks(x)
    ax.set_xticklabels([short_name(ck) for ck, _ in pairs], rotation=35, ha='right', fontsize=8)
    ax.set_ylabel('Position RMSE (m)', fontweight='bold')
    ax.set_title('Spoofing Robustness: Clean vs Spoofed Performance\n'
                 'Smaller gap means stronger robustness',
                 fontsize=14, fontweight='bold', pad=12)
    ax.grid(True, axis='y')
    ax.legend(fontsize=11)

    for i, (cv, sv) in enumerate(zip(clean_vals, spoof_vals)):
        deg = (sv - cv) / cv * 100 if cv > 0 else 0
        ax.text(i, max(cv, sv) + 0.1, f'+{deg:.0f}%', ha='center',
                fontsize=7, fontweight='bold', color=C['attack'])

plt.savefig('fig13_spoofing_robustness.png', dpi=300, bbox_inches='tight')
plt.show()
print("Spoofing robustness")

hm_keys = sorted(clean_keys, key=lambda x: rmse_s(ALL[x])['pm'])
hm = np.array([[np.sqrt(np.mean(ALL[k][s]['errors'] ** 2)) for s in sids] for k in hm_keys])

fig, ax = plt.subplots(figsize=(max(10, len(sids) * 0.8), max(5, len(hm_keys) * 0.4)))
im = ax.imshow(hm, cmap='RdYlGn_r', aspect='auto')
ax.set_xticks(range(len(sids)))
ax.set_xticklabels([f'S{s}' for s in sids], fontsize=9)
ax.set_yticks(range(len(hm_keys)))
ax.set_yticklabels([short_name(k) for k in hm_keys], fontsize=8)

thr = np.percentile(hm, 65)
for i in range(hm.shape[0]):
    for j in range(hm.shape[1]):
        c = 'white' if hm[i, j] > thr else 'black'
        ax.text(j, i, f'{hm[i, j]:.2f}', ha='center', va='center',
                fontsize=6, color=c, fontweight='bold')

plt.colorbar(im, ax=ax, label='Position RMSE (m)', fraction=0.03, pad=0.04)
ax.set_title('Per-Scene RMSE Heatmap — All Clean Methods\n'
             'Green = low error | Red = high error',
             fontsize=13, fontweight='bold', pad=12)
plt.savefig('fig14_heatmap.png', dpi=300, bbox_inches='tight')
plt.show()
print("Heatmap")


fig = plt.figure(figsize=(24, 14))
gs = gridspec.GridSpec(2, 3, hspace=0.4, wspace=0.35)

# A: Classification
ax1 = fig.add_subplot(gs[0, 0])
top_cl = sorted(results.items(), key=lambda x: x[1], reverse=True)[:7]
cc = ['#6C3483' if 'Neuro' in n else '#148F77' if '3-Sensor' in n else '#2471A3' for n, _ in top_cl]

ax1.barh(range(len(top_cl)), [v * 100 for _, v in top_cl], color=cc,
         edgecolor='white', height=0.6, alpha=0.88)
ax1.set_yticks(range(len(top_cl)))
ax1.set_yticklabels([n for n, _ in top_cl], fontsize=9)
ax1.axvline(98.98, color=C['attack'], linestyle='--', linewidth=1.5)
ax1.set_title('Phase 1: Classification', fontsize=12, fontweight='bold')
ax1.invert_yaxis()
ax1.grid(True, axis='x')

for i, (n, v) in enumerate(top_cl):
    ax1.text(v * 100 + 0.3, i, f'{v * 100:.1f}%', va='center', fontsize=9, fontweight='bold')

# B: State estimation ranked
ax2 = fig.add_subplot(gs[0, 1:])
top_ranked = ranked[:12]
top_names = [n for n, in top_ranked]
top_pos_vals = [v['pos'] for , v in top_ranked]
cr = cols_r[:len(top_ranked)]

ax2.barh(range(len(top_ranked)), top_pos_vals, color=cr,
         edgecolor='white', height=0.6, alpha=0.88)
ax2.set_yticks(range(len(top_ranked)))
ax2.set_yticklabels([short_name(n) for n in top_names], fontsize=10)
ax2.set_xlabel('Position RMSE (m)', fontweight='bold')
ax2.set_title('Phase 2: Top Methods Ranked', fontsize=12, fontweight='bold')
ax2.invert_yaxis()
ax2.grid(True, axis='x')

for i, (n, v) in enumerate(top_ranked):
    imp = (ekf_rmse - v['pos']) / ekf_rmse * 100
    ax2.text(v['pos'] + 0.01, i, f'{v["pos"]:.3f}m ({imp:+.0f}%)',
             va='center', fontsize=8, fontweight='bold')

# C: Best trajectory
ax3 = fig.add_subplot(gs[1, 0])
best_k = ranked[0][0]
gt = ALL['EKF'][sid0]['ground_truth']

style_method_line(ax3, gt[:, 0], gt[:, 1], C['gt'], 'Ground Truth',
                  lw=4.0, ls='-', alpha=1.0, z=10)
style_method_line(ax3, ALL['EKF'][sid0]['estimates'][:, 0], ALL['EKF'][sid0]['estimates'][:, 1],
                  C['ekf'], 'EKF', lw=1.8, ls='--', alpha=0.75)

if best_k in ALL and sid0 in ALL[best_k]:
    be = ALL[best_k][sid0]['estimates']
    br = scene_rmse(best_k, sid0)
    style_method_line(ax3, be[:, 0], be[:, 1], C['defense'],
                      f'{best_k} ({br:.3f}m)', lw=3.0, ls='-', alpha=0.95)

add_start_end(ax3, gt, add_labels=False)
ax3.legend(fontsize=8)
ax3.set_title(f'Best Trajectory: {best_k}', fontsize=11, fontweight='bold')
ax3.set_xlabel('X (m)')
ax3.set_ylabel('Y (m)')
ax3.grid(True)
maybe_equal_axis(ax3, gt[:, 0], gt[:, 1])

# D: Spoofing summary
ax4 = fig.add_subplot(gs[1, 1])
if pairs:
    deg_list = []
    for ck, sk in pairs:
        clean_rmse = rmse_s(ALL[ck])['pm']
        spoof_rmse = rmse_s(ALL[sk])['pm']
        deg = (spoof_rmse - clean_rmse) / clean_rmse * 100 if clean_rmse > 0 else 0
        deg_list.append((ck, deg))

    deg_list.sort(key=lambda x: x[1])
    top5 = deg_list[:5]

    ax4.barh(range(len(top5)), [d for _, d in top5],
             color=[C['defense'] if d < 50 else C['accent'] if d < 100 else C['attack'] for _, d in top5],
             edgecolor='white', height=0.6, alpha=0.88)
    ax4.set_yticks(range(len(top5)))
    ax4.set_yticklabels([short_name(n) for n, _ in top5], fontsize=9)
    ax4.set_xlabel('Degradation Under Spoofing (%)')
    ax4.set_title('Most Robust Methods\n(Lower = Better)', fontsize=11, fontweight='bold')
    ax4.invert_yaxis()
    ax4.grid(True, axis='x')

    for i, (n, d) in enumerate(top5):
        ax4.text(d + 1, i, f'{d:.0f}%', va='center', fontsize=9, fontweight='bold')
else:
    ax4.axis('off')

# E: Key findings
ax5 = fig.add_subplot(gs[1, 2])
ax5.axis('off')

bc = max(results.items(), key=lambda x: x[1])
best_state_name = ranked[0][0]
best_state_rmse = ranked[0][1]['pos']
best_improvement = (ekf_rmse - best_state_rmse) / ekf_rmse * 100

txt = [
    "KEY FINDINGS",
    "=" * 35,
    "",
    "CLASSIFICATION (Phase 1):",
    "STATE ESTIMATION (Phase 2):",
    f"  Best: {best_state_name}",
    f"  RMSE: {best_state_rmse:.4f} m",
    f"  EKF baseline: {ekf_rmse:.4f} m",
    f"  Improvement: {best_improvement:.1f}%",
    "",
    f"TOTAL METHODS: {len(ALL)}",
    f"  Clean: {len(clean_keys)}",
    f"  Spoofed: {len([k for k in ALL if 'spoofed' in k.lower()])}",
]

ax5.text(0.05, 0.95, '\n'.join(txt),
         transform=ax5.transAxes,
         fontsize=10,
         va='top',
         fontfamily='monospace',
         bbox=dict(boxstyle='round', facecolor='#F8F9FA', edgecolor=C['gt']))

plt.suptitle('COMPREHENSIVE RESULTS DASHBOARD',
             fontsize=16, fontweight='bold', y=1.01,
             bbox=dict(boxstyle='round', facecolor=C['gt'], alpha=0.9), color='white')
plt.savefig('fig15_dashboard.png', dpi=300, bbox_inches='tight')
plt.show()
print("Dashboard")


best_k = ranked[0][0]
fig, axes = plt.subplots(1, 2, figsize=(18, 7))

for ai, sid in enumerate(sids[:2]):
    ax = axes[ai]
    gt = ALL['EKF'][sid]['ground_truth']
    ekf = ALL['EKF'][sid]['estimates']
    best = ALL[best_k][sid]['estimates']

    style_method_line(ax, gt[:, 0], gt[:, 1], C['gt'], 'Ground Truth',
                      lw=4.0, ls='-', alpha=1.0, z=10)
    style_method_line(ax, ekf[:, 0], ekf[:, 1], C['ekf'],
                      f'EKF ({scene_rmse("EKF", sid):.3f}m)',
                      lw=2.0, ls='--', alpha=0.85)
    style_method_line(ax, best[:, 0], best[:, 1], C['defense'],
                      f'{best_k} ({scene_rmse(best_k, sid):.3f}m)',
                      lw=3.2, ls='-', alpha=0.98)

    add_start_end(ax, gt, add_labels=(ai == 0))
    ax.set_title(f'Scene {sid}: EKF vs Best Method', fontsize=13, fontweight='bold')
    ax.set_xlabel('X Position (m)', fontweight='bold')
    ax.set_ylabel('Y Position (m)', fontweight='bold')
    ax.grid(True, alpha=0.25, linestyle='--')
    maybe_equal_axis(ax, gt[:, 0], gt[:, 1])
    ax.legend(fontsize=9, loc='best')

plt.suptitle('Best State Estimator Against EKF Baseline',
             fontsize=15, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('fig16_best_vs_ekf_clear.png', dpi=300, bbox_inches='tight')
plt.show()
print("EKF vs best method")


rows = []
for k in ALL:
    s = rmse_s(ALL[k])
    imp = (ekf_rmse - s['pm']) / ekf_rmse * 100
    condition = 'Spoofed' if 'spoofed' in k.lower() else 'Clean'
    rows.append({
        'Method': k,
        'Condition': condition,
        'Pos RMSE (m)': round(s['pm'], 4),
        'Vel RMSE (m/s)': round(s['vm'], 4),
        'vs EKF %': round(imp, 1)
    })

df_final = pd.DataFrame(rows).sort_values(['Condition', 'Pos RMSE (m)'])

print("\n" + "=" * 70)
print("  FINAL RESULTS TABLE")
print("=" * 70)
print(df_final.to_string(index=False))

df_final.to_csv('final_results.csv', index=False)

print(f"\nTotal: {len(ALL)} methods evaluated")
print("All figures and CSV saved.")


import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.gridspec as gridspec
import numpy as np
import os
from mpl_toolkits.mplot3d import Axes3D

os.makedirs('/content/drive/MyDrive/Missing_Plots', exist_ok=True)
SAVE = '/content/drive/MyDrive/Missing_Plots'
SCENE_ID = 0

plt.rcParams.update({
    'font.size': 11,
    'axes.titlesize': 12,
    'axes.labelsize': 11,
    'font.family': 'serif',
    'axes.grid': True,
    'grid.alpha': 0.3
})

sd = df_all[df_all['scene_id'] == SCENE_ID].reset_index(drop=True)
N  = len(sd)
t  = np.arange(N) * 0.5
gt = sd[['gps_x','gps_y','gps_z']].values

def get_agent(fn, algo):
    return TRAINED.get((fn, algo), None)

def run_baseline(FC, spoof=False):
    sp = SpoofAttack(N, seed=42) if spoof else None
    res = run_filter(FC, sd, spoof=sp)
    return np.array(res['estimates'])[:N, :3]

def run_agent(agent, FC, spoof=False):
    if agent is None:
        return np.zeros((N, 3))
    sp = SpoofAttack(N, seed=42) if spoof else None
    env = FilterEnv(sd, FC, spoof_prob=0.)
    if sp is not None:
        env.spoof = sp
    state = env.reset()
    ests = [env.filt.get_state()]
    done = False
    while not done:
        action = agent.act(state, ev=True)
        state, _, done, _ = env.step(action)
        ests.append(env.filt.get_state())
    return np.array(ests)[:N, :3]

def pos_err(est, g):
    n = min(len(est), len(g))
    e = est[:n] - g[:n]
    return np.sqrt(e[:,0]**2 + e[:,1]**2 + e[:,2]**2)

def rmse(est, g):
    n = min(len(est), len(g))
    return float(np.sqrt(((est[:n] - g[:n])**2).mean()))

def get_nis(FC, spoof=False):
    sp = SpoofAttack(N, seed=42) if spoof else None
    res = run_filter(FC, sd, spoof=sp)
    return np.array(res.get('nis', np.zeros(N)))[:N]

print("Collecting estimates")

ekf_cl  = run_baseline(EKF)
ukf_cl  = run_baseline(UKF)
ckf_cl  = run_baseline(CKF) if 'CKF' in globals() else ukf_cl.copy()

ekf_sp  = run_baseline(EKF, spoof=True)
ukf_sp  = run_baseline(UKF, spoof=True)
ckf_sp  = run_baseline(CKF, spoof=True) if 'CKF' in globals() else ukf_sp.copy()

sac_ekf = run_agent(get_agent('EKF','SAC'), EKF)
td3_ukf = run_agent(get_agent('UKF','TD3'), UKF)

ekf_sac_sp = run_agent(get_agent('EKF','SAC'), EKF, spoof=True)
ukf_td3_sp = run_agent(get_agent('UKF','TD3'), UKF, spoof=True)

sa_cl = run_agent(get_agent('UKF','TD3-SA'), UKF, spoof=False)
sa_sp = run_agent(get_agent('UKF','TD3-SA'), UKF, spoof=True)

nis_ukf_cl = get_nis(UKF, spoof=False)
nis_ukf_sp = get_nis(UKF, spoof=True)

R = {
    'EKF':      rmse(ekf_cl,  gt),
    'UKF':      rmse(ukf_cl,  gt),
    'CKF':      rmse(ckf_cl,  gt),
    'EKF+SAC':  rmse(sac_ekf, gt),
    'UKF+TD3':  rmse(td3_ukf, gt),
    'SA Clean': rmse(sa_cl,   gt),
    'SA Spoof': rmse(sa_sp,   gt),
}

ME = 3
print("Output figures")


TRAJ_STYLE = {
    'Ground Truth': dict(color='black',   marker='o', linestyle='-',  lw=3.4, ms=6),
    'EKF':          dict(color='#E67E22', marker='s', linestyle='--', lw=2.4, ms=6),
    'UKF':          dict(color='#8E44AD', marker='D', linestyle='--', lw=2.4, ms=6),
    'CKF':          dict(color='#1ABC9C', marker='^', linestyle='--', lw=2.4, ms=6),
    'EKF+SAC':      dict(color='#C0392B', marker='v', linestyle='-.', lw=2.5, ms=7),
    'UKF+TD3':      dict(color='#2471A3', marker='P', linestyle='-.', lw=2.7, ms=7),
    'Spoofed':      dict(color='#D35400', marker='X', linestyle=':',  lw=2.8, ms=8),
    'Defense':      dict(color='#27AE60', marker='*', linestyle=':',  lw=3.0, ms=10),
    'SA Clean':     dict(color='#E377C2', marker='h', linestyle='-.', lw=2.7, ms=8),
    'SA Spoof':     dict(color='#17BECF', marker='^', linestyle=':',  lw=2.8, ms=8),
}

def offset_xy(path, offset=(0.0, 0.0)):
    p = np.asarray(path).copy()
    p[:, 0] += offset[0]
    p[:, 1] += offset[1]
    return p

def plot_traj(ax, path, label, offset=(0.0, 0.0), markevery=3, alpha=0.95):
    p = offset_xy(path, offset)
    st = TRAJ_STYLE.get(label, dict(color='gray', marker='o', linestyle='-', lw=2, ms=5))

    ax.plot(
        p[:, 0], p[:, 1],
        label=label,
        color=st['color'],
        linestyle=st['linestyle'],
        linewidth=st['lw'],
        marker=st['marker'],
        markersize=st['ms'],
        markevery=markevery,
        markerfacecolor=st['color'],
        markeredgecolor='white',
        markeredgewidth=0.9,
        alpha=alpha
    )

def decorate_traj(ax, gt_arr, title):
    ax.scatter(gt_arr[0,0], gt_arr[0,1],
               s=180, c='limegreen', marker='*',
               edgecolors='black', linewidths=1.0,
               zorder=10, label='Start')

    ax.scatter(gt_arr[-1,0], gt_arr[-1,1],
               s=160, c='red', marker='X',
               edgecolors='black', linewidths=1.0,
               zorder=10, label='End')

    ax.set_title(title, fontsize=12, fontweight='bold')
    ax.set_xlabel('X Position (m)')
    ax.set_ylabel('Y Position (m)')
    ax.grid(True, alpha=0.35)
    ax.axis('equal')

def plot_3d_traj(ax, path, label, offset=(0.0, 0.0), markevery=3):
    p = offset_xy(path, offset)
    st = TRAJ_STYLE.get(label, dict(color='gray', marker='o', linestyle='-', lw=2, ms=5))
    ax.plot(
        p[:,0], p[:,1], t[:len(p)],
        label=label,
        color=st['color'],
        linestyle=st['linestyle'],
        linewidth=st['lw'],
        marker=st['marker'],
        markersize=st['ms'],
        markevery=markevery,
        markerfacecolor=st['color'],
        markeredgecolor='white',
        markeredgewidth=0.7,
        alpha=0.95
    )


fig, axes = plt.subplots(1, 2, figsize=(14, 6))
fig.suptitle(
    'Fig A: Phase 1 — Sensor Fusion Benefit\n'
    'Single Sensor vs Multi-Sensor Classification Accuracy',
    fontsize=13, fontweight='bold'
)

single = {'IMU Only':89.91, 'GPS Only':97.25, 'Radar Only':84.40}
multi  = {'IMU+GPS':97.25, 'IMU+Radar':88.99, 'GPS+Radar':97.25,
          '3-Sensor GB':99.08, 'Neuro Fusion':99.08}

s_names = list(single.keys())
s_vals  = list(single.values())
s_cols  = ['#d62728','#1f77b4','#2ca02c']

bars1 = axes[0].bar(
    s_names, s_vals,
    color=s_cols, edgecolor='k',
    lw=0.8, alpha=0.9, width=0.5
)

axes[0].axhline(
    y=98.98, color='orange',
    ls='--', lw=2,
    label='Paper 1 Reference (98.98%)'
)

axes[0].set_ylim(80, 102)
for bar, val in zip(bars1, s_vals):
    axes[0].text(
        bar.get_x()+bar.get_width()/2,
        val+0.2, f'{val:.2f}%',
        ha='center', va='bottom',
        fontsize=11, fontweight='bold'
    )

axes[0].set_ylabel('Accuracy (%)', fontsize=12)
axes[0].set_title('Single Sensor Classifiers', fontsize=11, fontweight='bold')
axes[0].legend(fontsize=9)
axes[0].grid(True, axis='y', alpha=0.3)
axes[0].tick_params(axis='x', rotation=10)

m_names = list(multi.keys())
m_vals  = list(multi.values())
m_cols  = ['#9467bd','#8c564b','#e377c2','#2ca02c','#17becf']

bars2 = axes[1].bar(
    m_names, m_vals,
    color=m_cols, edgecolor='k',
    lw=0.8, alpha=0.9, width=0.5
)

axes[1].axhline(
    y=98.98, color='orange',
    ls='--', lw=2,
    label='Paper 1 Reference (98.98%)'
)

axes[1].set_ylim(80, 102)
for bar, val in zip(bars2, m_vals):
    axes[1].text(
        bar.get_x()+bar.get_width()/2,
        val+0.2, f'{val:.2f}%',
        ha='center', va='bottom',
        fontsize=11, fontweight='bold'
    )

axes[1].set_ylabel('Accuracy (%)', fontsize=12)
axes[1].set_title('Multi-Sensor Fusion Classifiers', fontsize=11, fontweight='bold')
axes[1].legend(fontsize=9)
axes[1].grid(True, axis='y', alpha=0.3)
axes[1].tick_params(axis='x', rotation=10)

plt.tight_layout()
plt.savefig(f'{SAVE}/FigA_sensor_fusion_benefit.png', dpi=200, bbox_inches='tight')
plt.show()
print("Figure saved")


fig, axes = plt.subplots(2, 1, figsize=(10, 9), sharex=True)
fig.suptitle(
    'Fig B: Normalized Innovation Squared (NIS) vs Time — Scene 0\n'
    'GPS consistency monitor — spike signals spoofing attack',
    fontsize=13, fontweight='bold'
)

axes[0].plot(
    t, nis_ukf_cl,
    color='#1f77b4', ls='-', lw=2.5,
    marker='o', ms=5, markevery=ME,
    mfc='#1f77b4', mec='white', mew=0.8,
    label='UKF (Clean GPS)'
)

axes[0].axhline(
    y=7.815, color='k', ls='--', lw=2.5,
    label='χ² threshold = 7.815'
)

axes[0].fill_between(t, 0, 7.815, alpha=0.06, color='green',
                     label='Consistent Region')

axes[0].set_ylabel('NIS', fontsize=12)
axes[0].set_ylim(bottom=0)
axes[0].set_title('Clean GPS — NIS remains mostly consistent', fontsize=11, fontweight='bold')
axes[0].legend(fontsize=10)
axes[0].grid(True, alpha=0.3)

axes[1].axvspan(
    t[int(0.3*N)], t[int(0.7*N)],
    alpha=0.12, color='red',
    label='GPS Spoofing Window (30%–70%)'
)

axes[1].plot(
    t, nis_ukf_cl,
    color='#1f77b4', ls='-', lw=2,
    marker='o', ms=4, markevery=ME,
    mfc='#1f77b4', mec='white', mew=0.8,
    label='UKF Clean GPS'
)

axes[1].plot(
    t, nis_ukf_sp,
    color='#d62728', ls='-', lw=2.5,
    marker='^', ms=6, markevery=ME,
    mfc='#d62728', mec='white', mew=0.8,
    label='UKF Under GPS Spoofing'
)

axes[1].axhline(
    y=7.815, color='k', ls='--', lw=2.5,
    label='χ² threshold = 7.815'
)

axes[1].set_ylabel('NIS', fontsize=12)
axes[1].set_xlabel('Time (s)', fontsize=12)
axes[1].set_ylim(bottom=0)
axes[1].set_title('Spoofed GPS — NIS exceeds threshold during attack', fontsize=11, fontweight='bold')
axes[1].legend(fontsize=10)
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(f'{SAVE}/FigB_nis_clean_vs_spoofed.png', dpi=200, bbox_inches='tight')
plt.show()
print("Figure saved")


try:
    if 'motion_class' in sd.columns:
        mc = sd['motion_class'].values[:N]
    elif 'label' in sd.columns:
        mc = sd['label'].values[:N]
    else:
        mc = np.random.choice([0,1,2], N, p=[0.27,0.18,0.55])

    err_baseline = pos_err(ekf_cl, gt)
    err_best     = pos_err(td3_ukf, gt)

    regime_colors = {0:'#d62728', 1:'#1f77b4', 2:'#2ca02c'}
    regime_names  = {0:'Stopped', 1:'Cruising', 2:'Turning'}

    fig, axes = plt.subplots(3, 1, figsize=(12, 10), sharex=True)
    fig.suptitle(
        'Fig C: Regime-Aware Analysis: Position Error by Motion Class\n'
        'Motion labels from Phase 1 projected onto Phase 2 estimation behavior',
        fontsize=13, fontweight='bold'
    )

    for j in range(N-1):
        axes[0].axvspan(t[j], t[j+1], color=regime_colors[int(mc[j])], alpha=0.5)

    axes[0].set_xlim(t[0], t[-1])
    axes[0].set_yticks([])
    axes[0].set_ylabel('Motion\nClass')

    for cls, col, nm in [(0,'#d62728','Stopped'),
                         (1,'#1f77b4','Cruising'),
                         (2,'#2ca02c','Turning')]:
        axes[0].plot([], [], color=col, lw=8, alpha=0.6, label=nm)

    axes[0].legend(fontsize=10, loc='upper right', ncol=3)
    axes[0].set_title('Phase 1: Vehicle Motion Class per Timestep', fontweight='bold')

    for j in range(N-1):
        axes[1].fill_between(
            [t[j], t[j+1]],
            [err_baseline[j], err_baseline[j+1]],
            color=regime_colors[int(mc[j])],
            alpha=0.4
        )

    axes[1].plot(
        t, err_baseline,
        color='#7f7f7f', lw=2.0,
        label=f'EKF Baseline Error (RMSE={R["EKF"]:.3f} m)'
    )

    axes[1].set_ylabel('Position Error (m)')
    axes[1].set_title('EKF Baseline — fixed noise, no RL adaptation', fontweight='bold')
    axes[1].legend(fontsize=10)
    axes[1].grid(True, alpha=0.3)

    for j in range(N-1):
        axes[2].fill_between(
            [t[j], t[j+1]],
            [err_best[j], err_best[j+1]],
            color=regime_colors[int(mc[j])],
            alpha=0.4
        )

    axes[2].plot(
        t, err_best,
        color='#2471A3', lw=2.4,
        label=f'UKF+TD3 Error (RMSE={R["UKF+TD3"]:.3f} m)'
    )

    axes[2].set_ylabel('Position Error (m)')
    axes[2].set_xlabel('Time (s)')
    axes[2].set_title('UKF+TD3 — RL adaptive noise tuning', fontweight='bold')
    axes[2].legend(fontsize=10)
    axes[2].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(f'{SAVE}/FigC_regime_aware_error.png', dpi=200, bbox_inches='tight')
    plt.show()
    print("Fig C saved")

except Exception as e:
    print(f" ouput")

fig, axes = plt.subplots(1, 2, figsize=(16, 7), subplot_kw={'projection':'3d'})
fig.suptitle(
    'Fig D: 3D Trajectory (X–Y–Time) — Baseline vs Best Method',
    fontsize=13, fontweight='bold'
)

for ax, azim, title in zip(axes, [45, 135], ['View 1 (azim=45°)', 'View 2 (azim=135°)']):
    ax.view_init(elev=25, azim=azim)

    plot_3d_traj(ax, gt,      'Ground Truth', offset=(0.0, 0.0), markevery=ME)
    plot_3d_traj(ax, ekf_cl,  'EKF',          offset=(0.6, -0.6), markevery=ME)
    plot_3d_traj(ax, td3_ukf, 'UKF+TD3',      offset=(-0.6, 0.6), markevery=ME)

    ax.scatter(gt[0,0], gt[0,1], t[0],
               s=120, c='limegreen', marker='*',
               edgecolors='black', depthshade=False, label='Start')

    ax.scatter(gt[-1,0], gt[-1,1], t[-1],
               s=120, c='red', marker='X',
               edgecolors='black', depthshade=False, label='End')

    ax.set_xlabel('X Position (m)', labelpad=8)
    ax.set_ylabel('Y Position (m)', labelpad=8)
    ax.set_zlabel('Time (s)', labelpad=8)
    ax.set_title(title, fontsize=11, fontweight='bold')

    if azim == 45:
        ax.legend(loc='upper left', fontsize=8)

plt.tight_layout()
plt.savefig(f'{SAVE}/FigD_3D_xy_time_trajectory.png', dpi=200, bbox_inches='tight')
plt.show()
print("Figure saved")

fig, axes = plt.subplots(1, 3, figsize=(19, 7))
fig.suptitle(
    'Fig E: GPS Spoofing Attack — Trajectory Drift and Robustness Comparison\n'
    'Continuous marker paths with small visual offsets for clear comparison',
    fontsize=13, fontweight='bold'
)

# Panel 1: KF baseline
plot_traj(axes[0], gt,     'Ground Truth', offset=(0.0, 0.0),  markevery=ME)
plot_traj(axes[0], ekf_cl, 'EKF',          offset=(0.6,-0.6),  markevery=ME)
plot_traj(axes[0], ekf_sp, 'Spoofed',      offset=(-0.6,0.6),  markevery=ME)
decorate_traj(axes[0], gt, 'EKF Baseline\nClean vs Spoofed GPS')
axes[0].legend(fontsize=8, loc='best')

# Panel 2: EKF + SAC
plot_traj(axes[1], gt,         'Ground Truth', offset=(0.0,0.0),   markevery=ME)
plot_traj(axes[1], sac_ekf,    'EKF+SAC',      offset=(0.6,-0.6),  markevery=ME)
plot_traj(axes[1], ekf_sac_sp, 'Spoofed',      offset=(-0.6,0.6),  markevery=ME)
decorate_traj(axes[1], gt, 'EKF + SAC\nClean vs Spoofed')
axes[1].legend(fontsize=8, loc='best')

# Panel 3: UKF + TD3 / spoof-aware result
plot_traj(axes[2], gt,    'Ground Truth', offset=(0.0,0.0),   markevery=ME)
plot_traj(axes[2], sa_cl, 'SA Clean',     offset=(0.6,-0.6),  markevery=ME)
plot_traj(axes[2], sa_sp, 'SA Spoof',     offset=(-0.6,0.6),  markevery=ME)
decorate_traj(axes[2], gt, 'UKF + TD3 Spoof-Aware\nClean vs Spoofed')
axes[2].legend(fontsize=8, loc='best')

plt.tight_layout()
plt.savefig(f'{SAVE}/FigE_spoofing_3panel.png', dpi=200, bbox_inches='tight')
plt.show()
print("Fig E saved")

fig, ax = plt.subplots(figsize=(11, 8))
fig.suptitle(
    'Fig H: Single Trajectory Map — Clean Estimation Comparison\n'
    'Ground Truth vs KF Baselines vs RL-Adaptive Methods',
    fontsize=13, fontweight='bold'
)

plot_traj(ax, gt,      'Ground Truth', offset=(0.0, 0.0),   markevery=ME)
plot_traj(ax, ekf_cl,  'EKF',          offset=(0.8,-0.8),   markevery=ME)
plot_traj(ax, ukf_cl,  'UKF',          offset=(-0.8,0.8),   markevery=ME)
plot_traj(ax, ckf_cl,  'CKF',          offset=(1.2,0.4),    markevery=ME)
plot_traj(ax, sac_ekf, 'EKF+SAC',      offset=(-1.2,-0.4),  markevery=ME)
plot_traj(ax, td3_ukf, 'UKF+TD3',      offset=(0.0,1.2),    markevery=ME)

decorate_traj(ax, gt, 'All Clean Methods on One Trajectory Map')
ax.legend(fontsize=9, ncol=2, loc='best')

plt.tight_layout()
plt.savefig(f'{SAVE}/FigH_all_clean_trajectory_map.png', dpi=200, bbox_inches='tight')
plt.show()
print("Figure saved")

fig, ax = plt.subplots(figsize=(11, 8))
fig.suptitle(
    'Fig I: Single Trajectory Map Spoofing Impact Comparison\n'
    'Clean tracking, spoofed tracking, and spoof-aware tracking',
    fontsize=13, fontweight='bold'
)

plot_traj(ax, gt,         'Ground Truth', offset=(0.0,0.0),    markevery=ME)
plot_traj(ax, td3_ukf,    'UKF+TD3',      offset=(0.8,-0.8),   markevery=ME)
plot_traj(ax, ukf_td3_sp, 'Spoofed',      offset=(-0.8,0.8),   markevery=ME)
plot_traj(ax, sa_sp,      'Defense',      offset=(0.0,1.2),    markevery=ME)

decorate_traj(ax, gt, 'Spoofing Robustness on One Trajectory Map')
ax.legend(fontsize=9, ncol=2, loc='best')

plt.tight_layout()
plt.savefig(f'{SAVE}/FigI_spoofing_single_trajectory_map.png', dpi=200, bbox_inches='tight')
plt.show()
print("Figure saved")

fig, axes = plt.subplots(2, 1, figsize=(11, 9), sharex=True)
fig.suptitle(
    'Fig F: Position Error vs Time, Baselines vs RL-Adaptive Methods\n'
    'Separated y-axes for clarity (Scene 0)',
    fontsize=13, fontweight='bold'
)

axes[0].plot(
    t, pos_err(ekf_cl, gt),
    color='#E67E22', ls='--', lw=2.5,
    marker='s', ms=5, markevery=ME,
    mfc='#E67E22', mec='w', mew=0.8,
    label=f'EKF ({R["EKF"]:.3f} m)'
)

axes[0].plot(
    t, pos_err(ukf_cl, gt),
    color='#8E44AD', ls='--', lw=2.5,
    marker='D', ms=5, markevery=ME,
    mfc='#8E44AD', mec='w', mew=0.8,
    label=f'UKF ({R["UKF"]:.3f} m)'
)

axes[0].plot(
    t, pos_err(ckf_cl, gt),
    color='#1ABC9C', ls='--', lw=2.5,
    marker='^', ms=5, markevery=ME,
    mfc='#1ABC9C', mec='w', mew=0.8,
    label=f'CKF ({R["CKF"]:.3f} m)'
)

axes[0].set_ylabel('Position Error (m)', fontsize=12)
axes[0].set_title('Fixed KF Baselines — no RL adaptation', fontsize=11, fontweight='bold')
axes[0].legend(fontsize=10)
axes[0].grid(True, alpha=0.3)
axes[0].set_facecolor('#fff9f9')

axes[1].plot(
    t, pos_err(sac_ekf, gt),
    color='#C0392B', ls='-', lw=2,
    marker='v', ms=5, markevery=ME,
    mfc='#C0392B', mec='w', mew=0.8,
    label=f'EKF+SAC ({R["EKF+SAC"]:.3f} m)'
)

axes[1].plot(
    t, pos_err(td3_ukf, gt),
    color='#2471A3', ls='-', lw=2.4,
    marker='P', ms=6, markevery=ME,
    mfc='#2471A3', mec='w', mew=0.8,
    label=f'UKF+TD3 ({R["UKF+TD3"]:.3f} m)'
)

axes[1].plot(
    t, pos_err(sa_cl, gt),
    color='#E377C2', ls='-', lw=2.8,
    marker='h', ms=7, markevery=ME,
    mfc='#E377C2', mec='w', mew=0.8,
    label=f'Spoof-aware Clean ({R["SA Clean"]:.3f} m)'
)

axes[1].set_ylabel('Position Error (m)', fontsize=12)
axes[1].set_xlabel('Time (s)', fontsize=12)
axes[1].set_title('RL-Adaptive KF Methods adaptive noise tuning', fontsize=11, fontweight='bold')
axes[1].legend(fontsize=10)
axes[1].grid(True, alpha=0.3)
axes[1].set_facecolor('#f9fff9')

pct = (R['EKF'] - R['UKF+TD3']) / R['EKF'] * 100
axes[0].annotate(
    f'RL reduces error\nby {pct:.1f}%',
    xy=(t[N//2], pos_err(ekf_cl,gt)[N//2]),
    xytext=(t[N//2]+3, pos_err(ekf_cl,gt)[N//2]+0.4),
    fontsize=9, color='green', fontweight='bold',
    arrowprops=dict(arrowstyle='->', color='green')
)

plt.tight_layout()
plt.savefig(f'{SAVE}/FigF_pos_error_separated.png', dpi=200, bbox_inches='tight')
plt.show()
print("Figure saved")

fig, ax = plt.subplots(figsize=(12, 5))
ax.axis('off')

fig.suptitle(
    'Fig G: Comparison with Reference Papers',
    fontsize=13, fontweight='bold'
)

columns = ['Method', 'Dataset', 'Phase 1\nAccuracy',
           'Phase 2\nPos RMSE', 'Spoofing\nAnalysis', 'Regime\nAware']

data = [
    ['Paper 1', 'Lab / HAR\nsensor fusion', '98.98%', 'N/A', 'No', 'No'],
    ['Paper 2', 'Simulated UAV\nKF + SAC', 'N/A', 'Reported in paper', 'Yes', 'No'],
    ['Our Phase 1', 'nuScenes\n3 classes, 3 sensors', '≈99%', 'N/A', 'No', 'Yes'],
    ['Our Phase 2', 'nuScenes\nKF + RL', 'N/A', f'{R["UKF+TD3"]:.3f} m', 'Yes', 'Yes'],
    ['Our Pipeline', 'nuScenes\nFusion + KF + RL', '≈99%', f'{R["UKF+TD3"]:.3f} m', 'Yes', 'Yes'],
]

table = ax.table(
    cellText=data,
    colLabels=columns,
    loc='center',
    cellLoc='center'
)

table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1.2, 2.2)

for j in range(len(columns)):
    table[(0,j)].set_facecolor('#2c3e50')
    table[(0,j)].set_text_props(color='white', fontweight='bold')

for i in [3,4,5]:
    for j in range(len(columns)):
        table[(i,j)].set_facecolor('#e8f8e8')

for i in [1,2]:
    for j in range(len(columns)):
        table[(i,j)].set_facecolor('#f8f8f8')

plt.tight_layout()
plt.savefig(f'{SAVE}/FigG_comparison_table.png', dpi=200, bbox_inches='tight')
plt.show()
print("Figure saved")

print("Execution Done")
print("\nFigure Summary:")
print("Sensor fusion")
print("NIS clean vs spoofed")
print("Regime-aware error by motion class")
print("3D X-Y-Time trajectory")
print("Clear marker-based spoofing trajectory panels")
print("Position error over time")
print("Comparison table")
print("Single trajectory map for clean methods")
print("Single trajectory map for spoofing impact")